#include "buffer_class.hpp"
#include "../internal/tools.hpp"
#include "../internal/modules.hpp"

#include "../limits.hpp"

/* Slot offsets of the Limits class */

PyTypeObject * Limits_class;
int Limits_class_point_size_range;
int Limits_class_smooth_line_width_range;
int Limits_class_aliased_line_width_range;
int Limits_class_point_fade_threshold_size;
int Limits_class_point_size_granularity;
int Limits_class_smooth_line_width_granularity;
int Limits_class_min_program_texel_offset;
int Limits_class_max_program_texel_offset;
int Limits_class_minor_version;
int Limits_class_major_version;
int Limits_class_sample_buffers;
int Limits_class_subpixel_bits;
int Limits_class_context_profile_mask;
int Limits_class_uniform_buffer_offset_alignment;
int Limits_class_max_viewport_dims;
int Limits_class_max_3d_texture_size;
int Limits_class_max_array_texture_layers;
int Limits_class_max_clip_distances;
int Limits_class_max_color_attachments;
int Limits_class_max_color_texture_samples;
int Limits_class_max_combined_fragment_uniform_components;
int Limits_class_max_combined_geometry_uniform_components;
int Limits_class_max_combined_texture_image_units;
int Limits_class_max_combined_uniform_blocks;
int Limits_class_max_combined_vertex_uniform_components;
int Limits_class_max_cube_map_texture_size;
int Limits_class_max_depth_texture_samples;
int Limits_class_max_draw_buffers;
int Limits_class_max_dual_source_draw_buffers;
int Limits_class_max_elements_indices;
int Limits_class_max_elements_vertices;
int Limits_class_max_fragment_input_components;
int Limits_class_max_fragment_uniform_components;
int Limits_class_max_fragment_uniform_vectors;
int Limits_class_max_fragment_uniform_blocks;
int Limits_class_max_geometry_input_components;
int Limits_class_max_geometry_output_components;
int Limits_class_max_geometry_texture_image_units;
int Limits_class_max_geometry_uniform_blocks;
int Limits_class_max_geometry_uniform_components;
int Limits_class_max_integer_samples;
int Limits_class_max_samples;
int Limits_class_max_rectangle_texture_size;
int Limits_class_max_renderbuffer_size;
int Limits_class_max_sample_mask_words;
int Limits_class_max_texture_buffer_size;
int Limits_class_max_texture_image_units;
int Limits_class_max_texture_lod_bias;
int Limits_class_max_texture_size;
int Limits_class_max_uniform_buffer_bindings;
int Limits_class_max_uniform_block_size;
int Limits_class_max_varying_components;
int Limits_class_max_varying_vectors;
int Limits_class_max_varying_floats;
int Limits_class_max_vertex_attribs;
int Limits_class_max_vertex_texture_image_units;
int Limits_class_max_vertex_uniform_components;
int Limits_class_max_vertex_uniform_vectors;
int Limits_class_max_vertex_output_components;
int Limits_class_max_vertex_uniform_blocks;
int Limits_class_max_vertex_attrib_relative_offset;
int Limits_class_max_vertex_attrib_bindings;
int Limits_class_max_server_wait_timeout;
int Limits_class_viewport_bounds_range;
int Limits_class_viewport_subpixel_bits;
int Limits_class_max_viewports;
int Limits_class_min_map_buffer_alignment;
int Limits_class_max_combined_atomic_counters;
int Limits_class_max_fragment_atomic_counters;
int Limits_class_max_geometry_atomic_counters;
int Limits_class_max_tess_control_atomic_counters;
int Limits_class_max_tess_evaluation_atomic_counters;
int Limits_class_max_vertex_atomic_counters;
int Limits_class_max_shader_storage_buffer_bindings;
int Limits_class_max_combined_shader_storage_blocks;
int Limits_class_max_vertex_shader_storage_blocks;
int Limits_class_max_fragment_shader_storage_blocks;
int Limits_class_max_geometry_shader_storage_blocks;
int Limits_class_max_tess_evaluation_shader_storage_blocks;
int Limits_class_max_tess_control_shader_storage_blocks;
int Limits_class_max_compute_shader_storage_blocks;
int Limits_class_max_compute_uniform_components;
int Limits_class_max_compute_atomic_counters;
int Limits_class_max_compute_atomic_counter_buffers;
int Limits_class_max_compute_work_group_invocations;
int Limits_class_max_compute_uniform_blocks;
int Limits_class_max_compute_texture_image_units;
int Limits_class_max_combined_compute_uniform_components;
int Limits_class_max_framebuffer_width;
int Limits_class_max_framebuffer_height;
int Limits_class_max_framebuffer_layers;
int Limits_class_max_framebuffer_samples;
int Limits_class_max_uniform_locations;
int Limits_class_max_element_index;
int Limits_class_max_shader_storage_block_size;

/* Detect Limits wrapper class */

void MGLLimits_init_wrapper() {
    int Limits_slots = 0;
    Limits_class = detect_class(moderngl, "Limits", Limits_slots);
    Limits_class_point_size_range = slot_offset(Limits_class, "point_size_range", Limits_slots);
    Limits_class_smooth_line_width_range = slot_offset(Limits_class, "smooth_line_width_range", Limits_slots);
    Limits_class_aliased_line_width_range = slot_offset(Limits_class, "aliased_line_width_range", Limits_slots);
    Limits_class_point_fade_threshold_size = slot_offset(Limits_class, "point_fade_threshold_size", Limits_slots);
    Limits_class_point_size_granularity = slot_offset(Limits_class, "point_size_granularity", Limits_slots);
    Limits_class_smooth_line_width_granularity = slot_offset(Limits_class, "smooth_line_width_granularity", Limits_slots);
    Limits_class_min_program_texel_offset = slot_offset(Limits_class, "min_program_texel_offset", Limits_slots);
    Limits_class_max_program_texel_offset = slot_offset(Limits_class, "max_program_texel_offset", Limits_slots);
    Limits_class_minor_version = slot_offset(Limits_class, "minor_version", Limits_slots);
    Limits_class_major_version = slot_offset(Limits_class, "major_version", Limits_slots);
    Limits_class_sample_buffers = slot_offset(Limits_class, "sample_buffers", Limits_slots);
    Limits_class_subpixel_bits = slot_offset(Limits_class, "subpixel_bits", Limits_slots);
    Limits_class_context_profile_mask = slot_offset(Limits_class, "context_profile_mask", Limits_slots);
    Limits_class_uniform_buffer_offset_alignment = slot_offset(Limits_class, "uniform_buffer_offset_alignment", Limits_slots);
    Limits_class_max_viewport_dims = slot_offset(Limits_class, "max_viewport_dims", Limits_slots);
    Limits_class_max_3d_texture_size = slot_offset(Limits_class, "max_3d_texture_size", Limits_slots);
    Limits_class_max_array_texture_layers = slot_offset(Limits_class, "max_array_texture_layers", Limits_slots);
    Limits_class_max_clip_distances = slot_offset(Limits_class, "max_clip_distances", Limits_slots);
    Limits_class_max_color_attachments = slot_offset(Limits_class, "max_color_attachments", Limits_slots);
    Limits_class_max_color_texture_samples = slot_offset(Limits_class, "max_color_texture_samples", Limits_slots);
    Limits_class_max_combined_fragment_uniform_components = slot_offset(Limits_class, "max_combined_fragment_uniform_components", Limits_slots);
    Limits_class_max_combined_geometry_uniform_components = slot_offset(Limits_class, "max_combined_geometry_uniform_components", Limits_slots);
    Limits_class_max_combined_texture_image_units = slot_offset(Limits_class, "max_combined_texture_image_units", Limits_slots);
    Limits_class_max_combined_uniform_blocks = slot_offset(Limits_class, "max_combined_uniform_blocks", Limits_slots);
    Limits_class_max_combined_vertex_uniform_components = slot_offset(Limits_class, "max_combined_vertex_uniform_components", Limits_slots);
    Limits_class_max_cube_map_texture_size = slot_offset(Limits_class, "max_cube_map_texture_size", Limits_slots);
    Limits_class_max_depth_texture_samples = slot_offset(Limits_class, "max_depth_texture_samples", Limits_slots);
    Limits_class_max_draw_buffers = slot_offset(Limits_class, "max_draw_buffers", Limits_slots);
    Limits_class_max_dual_source_draw_buffers = slot_offset(Limits_class, "max_dual_source_draw_buffers", Limits_slots);
    Limits_class_max_elements_indices = slot_offset(Limits_class, "max_elements_indices", Limits_slots);
    Limits_class_max_elements_vertices = slot_offset(Limits_class, "max_elements_vertices", Limits_slots);
    Limits_class_max_fragment_input_components = slot_offset(Limits_class, "max_fragment_input_components", Limits_slots);
    Limits_class_max_fragment_uniform_components = slot_offset(Limits_class, "max_fragment_uniform_components", Limits_slots);
    Limits_class_max_fragment_uniform_vectors = slot_offset(Limits_class, "max_fragment_uniform_vectors", Limits_slots);
    Limits_class_max_fragment_uniform_blocks = slot_offset(Limits_class, "max_fragment_uniform_blocks", Limits_slots);
    Limits_class_max_geometry_input_components = slot_offset(Limits_class, "max_geometry_input_components", Limits_slots);
    Limits_class_max_geometry_output_components = slot_offset(Limits_class, "max_geometry_output_components", Limits_slots);
    Limits_class_max_geometry_texture_image_units = slot_offset(Limits_class, "max_geometry_texture_image_units", Limits_slots);
    Limits_class_max_geometry_uniform_blocks = slot_offset(Limits_class, "max_geometry_uniform_blocks", Limits_slots);
    Limits_class_max_geometry_uniform_components = slot_offset(Limits_class, "max_geometry_uniform_components", Limits_slots);
    Limits_class_max_integer_samples = slot_offset(Limits_class, "max_integer_samples", Limits_slots);
    Limits_class_max_samples = slot_offset(Limits_class, "max_samples", Limits_slots);
    Limits_class_max_rectangle_texture_size = slot_offset(Limits_class, "max_rectangle_texture_size", Limits_slots);
    Limits_class_max_renderbuffer_size = slot_offset(Limits_class, "max_renderbuffer_size", Limits_slots);
    Limits_class_max_sample_mask_words = slot_offset(Limits_class, "max_sample_mask_words", Limits_slots);
    Limits_class_max_texture_buffer_size = slot_offset(Limits_class, "max_texture_buffer_size", Limits_slots);
    Limits_class_max_texture_image_units = slot_offset(Limits_class, "max_texture_image_units", Limits_slots);
    Limits_class_max_texture_lod_bias = slot_offset(Limits_class, "max_texture_lod_bias", Limits_slots);
    Limits_class_max_texture_size = slot_offset(Limits_class, "max_texture_size", Limits_slots);
    Limits_class_max_uniform_buffer_bindings = slot_offset(Limits_class, "max_uniform_buffer_bindings", Limits_slots);
    Limits_class_max_uniform_block_size = slot_offset(Limits_class, "max_uniform_block_size", Limits_slots);
    Limits_class_max_varying_components = slot_offset(Limits_class, "max_varying_components", Limits_slots);
    Limits_class_max_varying_vectors = slot_offset(Limits_class, "max_varying_vectors", Limits_slots);
    Limits_class_max_varying_floats = slot_offset(Limits_class, "max_varying_floats", Limits_slots);
    Limits_class_max_vertex_attribs = slot_offset(Limits_class, "max_vertex_attribs", Limits_slots);
    Limits_class_max_vertex_texture_image_units = slot_offset(Limits_class, "max_vertex_texture_image_units", Limits_slots);
    Limits_class_max_vertex_uniform_components = slot_offset(Limits_class, "max_vertex_uniform_components", Limits_slots);
    Limits_class_max_vertex_uniform_vectors = slot_offset(Limits_class, "max_vertex_uniform_vectors", Limits_slots);
    Limits_class_max_vertex_output_components = slot_offset(Limits_class, "max_vertex_output_components", Limits_slots);
    Limits_class_max_vertex_uniform_blocks = slot_offset(Limits_class, "max_vertex_uniform_blocks", Limits_slots);
    Limits_class_max_vertex_attrib_relative_offset = slot_offset(Limits_class, "max_vertex_attrib_relative_offset", Limits_slots);
    Limits_class_max_vertex_attrib_bindings = slot_offset(Limits_class, "max_vertex_attrib_bindings", Limits_slots);
    Limits_class_max_server_wait_timeout = slot_offset(Limits_class, "max_server_wait_timeout", Limits_slots);
    Limits_class_viewport_bounds_range = slot_offset(Limits_class, "viewport_bounds_range", Limits_slots);
    Limits_class_viewport_subpixel_bits = slot_offset(Limits_class, "viewport_subpixel_bits", Limits_slots);
    Limits_class_max_viewports = slot_offset(Limits_class, "max_viewports", Limits_slots);
    Limits_class_min_map_buffer_alignment = slot_offset(Limits_class, "min_map_buffer_alignment", Limits_slots);
    Limits_class_max_combined_atomic_counters = slot_offset(Limits_class, "max_combined_atomic_counters", Limits_slots);
    Limits_class_max_fragment_atomic_counters = slot_offset(Limits_class, "max_fragment_atomic_counters", Limits_slots);
    Limits_class_max_geometry_atomic_counters = slot_offset(Limits_class, "max_geometry_atomic_counters", Limits_slots);
    Limits_class_max_tess_control_atomic_counters = slot_offset(Limits_class, "max_tess_control_atomic_counters", Limits_slots);
    Limits_class_max_tess_evaluation_atomic_counters = slot_offset(Limits_class, "max_tess_evaluation_atomic_counters", Limits_slots);
    Limits_class_max_vertex_atomic_counters = slot_offset(Limits_class, "max_vertex_atomic_counters", Limits_slots);
    Limits_class_max_shader_storage_buffer_bindings = slot_offset(Limits_class, "max_shader_storage_buffer_bindings", Limits_slots);
    Limits_class_max_combined_shader_storage_blocks = slot_offset(Limits_class, "max_combined_shader_storage_blocks", Limits_slots);
    Limits_class_max_vertex_shader_storage_blocks = slot_offset(Limits_class, "max_vertex_shader_storage_blocks", Limits_slots);
    Limits_class_max_fragment_shader_storage_blocks = slot_offset(Limits_class, "max_fragment_shader_storage_blocks", Limits_slots);
    Limits_class_max_geometry_shader_storage_blocks = slot_offset(Limits_class, "max_geometry_shader_storage_blocks", Limits_slots);
    Limits_class_max_tess_evaluation_shader_storage_blocks = slot_offset(Limits_class, "max_tess_evaluation_shader_storage_blocks", Limits_slots);
    Limits_class_max_tess_control_shader_storage_blocks = slot_offset(Limits_class, "max_tess_control_shader_storage_blocks", Limits_slots);
    Limits_class_max_compute_shader_storage_blocks = slot_offset(Limits_class, "max_compute_shader_storage_blocks", Limits_slots);
    Limits_class_max_compute_uniform_components = slot_offset(Limits_class, "max_compute_uniform_components", Limits_slots);
    Limits_class_max_compute_atomic_counters = slot_offset(Limits_class, "max_compute_atomic_counters", Limits_slots);
    Limits_class_max_compute_atomic_counter_buffers = slot_offset(Limits_class, "max_compute_atomic_counter_buffers", Limits_slots);
    Limits_class_max_compute_work_group_invocations = slot_offset(Limits_class, "max_compute_work_group_invocations", Limits_slots);
    Limits_class_max_compute_uniform_blocks = slot_offset(Limits_class, "max_compute_uniform_blocks", Limits_slots);
    Limits_class_max_compute_texture_image_units = slot_offset(Limits_class, "max_compute_texture_image_units", Limits_slots);
    Limits_class_max_combined_compute_uniform_components = slot_offset(Limits_class, "max_combined_compute_uniform_components", Limits_slots);
    Limits_class_max_framebuffer_width = slot_offset(Limits_class, "max_framebuffer_width", Limits_slots);
    Limits_class_max_framebuffer_height = slot_offset(Limits_class, "max_framebuffer_height", Limits_slots);
    Limits_class_max_framebuffer_layers = slot_offset(Limits_class, "max_framebuffer_layers", Limits_slots);
    Limits_class_max_framebuffer_samples = slot_offset(Limits_class, "max_framebuffer_samples", Limits_slots);
    Limits_class_max_uniform_locations = slot_offset(Limits_class, "max_uniform_locations", Limits_slots);
    Limits_class_max_element_index = slot_offset(Limits_class, "max_element_index", Limits_slots);
    Limits_class_max_shader_storage_block_size = slot_offset(Limits_class, "max_shader_storage_block_size", Limits_slots);
    assert_slots_len(Limits_class, Limits_slots);
}
