FROM ubuntu:22.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y curl git lz4 python3 python3-pip unzip
RUN curl -sL https://github.com/pygame-web/python-wasm-sdk/releases/download/3.1.46.bi/python3.11-wasm-sdk-Ubuntu-22.04.tar.lz4 -o sdk.tar.lz4 &&\
    tar xfP sdk.tar.lz4 --use-compress-program=lz4 &&\
    rm sdk.tar.lz4
RUN python3 -m pip install pygbag==0.8.6

COPY src /moderngl/src
COPY moderngl /moderngl/moderngl
COPY moderngl-stubs /moderngl/moderngl-stubs
COPY setup.py MANIFEST.in LICENSE README.md _moderngl.py /moderngl/
RUN cd /moderngl/ && /opt/python-wasm-sdk/python3-wasm setup.py bdist_wheel
RUN unzip /moderngl/dist/moderngl-6.0.0-cp311-cp311-wasm32_bi_emscripten.whl -d /web/

COPY examples/pygame-web/main.py /web/
RUN sed -i 's/args.bind/"0.0.0.0"/g' /usr/local/lib/python3.10/dist-packages/pygbag/testserver.py
CMD python3 -m pygbag --template noctx.tmpl /web/

# podman build -f examples/pygame-web/Containerfile . -t temp && podman run --rm -it -p 127.0.0.1:8000:8000 temp
# http://localhost:8000/?-i
