#include "gl_methods.hpp"

#if defined(_WIN32) || defined(_WIN64)

#define PREFIX ""

#include <Windows.h>

#ifdef MemoryBarrier
#undef MemoryBarrier
#endif

void * LoadMethod(const char * method) {
	static HMODULE opengl32 = LoadLibrary("opengl32.dll");

	void * proc = (void *)GetProcAddress(opengl32, method);

	if (proc) {
		return proc;
	}

	proc = (void *)wglGetProcAddress(method);

	if (proc) {
		return proc;
	}

	return 0;
}

#elif defined(__APPLE__)

#define PREFIX "_"

#import <mach-o/dyld.h>
#import <stdlib.h>
#import <string.h>

void * LoadMethod(const char * method) {
	NSSymbol symbol = 0;

	if (NSIsSymbolNameDefined(method)) {
		symbol = NSLookupAndBindSymbol(method);
	}

	return symbol ? NSAddressOfSymbol(symbol) : 0;
}

#else

#define PREFIX ""

#include <dlfcn.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>

typedef const void * (* PROC_glXGetProcAddress)(const char *);

void * LoadMethod(const char * method) {
	static void * libgl = dlopen("libGL.so.1", RTLD_LAZY);
	static PROC_glXGetProcAddress glXGetProcAddress = (PROC_glXGetProcAddress)dlsym(libgl, "glXGetProcAddress");

	void * proc = (void *)dlsym(libgl, method);

	if (proc) {
		return proc;
	}

	proc = (void *)glXGetProcAddress(method);

	if (proc) {
		return proc;
	}

	return 0;
}

#endif

bool GLMethods::load() {
	this->CullFace = (PROC_glCullFace)LoadMethod(PREFIX "glCullFace");
	this->FrontFace = (PROC_glFrontFace)LoadMethod(PREFIX "glFrontFace");
	this->Hint = (PROC_glHint)LoadMethod(PREFIX "glHint");
	this->LineWidth = (PROC_glLineWidth)LoadMethod(PREFIX "glLineWidth");
	this->PointSize = (PROC_glPointSize)LoadMethod(PREFIX "glPointSize");
	this->PolygonMode = (PROC_glPolygonMode)LoadMethod(PREFIX "glPolygonMode");
	this->Scissor = (PROC_glScissor)LoadMethod(PREFIX "glScissor");
	this->TexParameterf = (PROC_glTexParameterf)LoadMethod(PREFIX "glTexParameterf");
	this->TexParameterfv = (PROC_glTexParameterfv)LoadMethod(PREFIX "glTexParameterfv");
	this->TexParameteri = (PROC_glTexParameteri)LoadMethod(PREFIX "glTexParameteri");
	this->TexParameteriv = (PROC_glTexParameteriv)LoadMethod(PREFIX "glTexParameteriv");
	this->TexImage1D = (PROC_glTexImage1D)LoadMethod(PREFIX "glTexImage1D");
	this->TexImage2D = (PROC_glTexImage2D)LoadMethod(PREFIX "glTexImage2D");
	this->DrawBuffer = (PROC_glDrawBuffer)LoadMethod(PREFIX "glDrawBuffer");
	this->Clear = (PROC_glClear)LoadMethod(PREFIX "glClear");
	this->ClearColor = (PROC_glClearColor)LoadMethod(PREFIX "glClearColor");
	this->ClearStencil = (PROC_glClearStencil)LoadMethod(PREFIX "glClearStencil");
	this->ClearDepth = (PROC_glClearDepth)LoadMethod(PREFIX "glClearDepth");
	this->StencilMask = (PROC_glStencilMask)LoadMethod(PREFIX "glStencilMask");
	this->ColorMask = (PROC_glColorMask)LoadMethod(PREFIX "glColorMask");
	this->DepthMask = (PROC_glDepthMask)LoadMethod(PREFIX "glDepthMask");
	this->Disable = (PROC_glDisable)LoadMethod(PREFIX "glDisable");
	this->Enable = (PROC_glEnable)LoadMethod(PREFIX "glEnable");
	this->Finish = (PROC_glFinish)LoadMethod(PREFIX "glFinish");
	this->Flush = (PROC_glFlush)LoadMethod(PREFIX "glFlush");
	this->BlendFunc = (PROC_glBlendFunc)LoadMethod(PREFIX "glBlendFunc");
	this->LogicOp = (PROC_glLogicOp)LoadMethod(PREFIX "glLogicOp");
	this->StencilFunc = (PROC_glStencilFunc)LoadMethod(PREFIX "glStencilFunc");
	this->StencilOp = (PROC_glStencilOp)LoadMethod(PREFIX "glStencilOp");
	this->DepthFunc = (PROC_glDepthFunc)LoadMethod(PREFIX "glDepthFunc");
	this->PixelStoref = (PROC_glPixelStoref)LoadMethod(PREFIX "glPixelStoref");
	this->PixelStorei = (PROC_glPixelStorei)LoadMethod(PREFIX "glPixelStorei");
	this->ReadBuffer = (PROC_glReadBuffer)LoadMethod(PREFIX "glReadBuffer");
	this->ReadPixels = (PROC_glReadPixels)LoadMethod(PREFIX "glReadPixels");
	this->GetBooleanv = (PROC_glGetBooleanv)LoadMethod(PREFIX "glGetBooleanv");
	this->GetDoublev = (PROC_glGetDoublev)LoadMethod(PREFIX "glGetDoublev");
	this->GetError = (PROC_glGetError)LoadMethod(PREFIX "glGetError");
	this->GetFloatv = (PROC_glGetFloatv)LoadMethod(PREFIX "glGetFloatv");
	this->GetIntegerv = (PROC_glGetIntegerv)LoadMethod(PREFIX "glGetIntegerv");
	this->GetString = (PROC_glGetString)LoadMethod(PREFIX "glGetString");
	this->GetTexImage = (PROC_glGetTexImage)LoadMethod(PREFIX "glGetTexImage");
	this->GetTexParameterfv = (PROC_glGetTexParameterfv)LoadMethod(PREFIX "glGetTexParameterfv");
	this->GetTexParameteriv = (PROC_glGetTexParameteriv)LoadMethod(PREFIX "glGetTexParameteriv");
	this->GetTexLevelParameterfv = (PROC_glGetTexLevelParameterfv)LoadMethod(PREFIX "glGetTexLevelParameterfv");
	this->GetTexLevelParameteriv = (PROC_glGetTexLevelParameteriv)LoadMethod(PREFIX "glGetTexLevelParameteriv");
	this->IsEnabled = (PROC_glIsEnabled)LoadMethod(PREFIX "glIsEnabled");
	this->DepthRange = (PROC_glDepthRange)LoadMethod(PREFIX "glDepthRange");
	this->Viewport = (PROC_glViewport)LoadMethod(PREFIX "glViewport");
	this->DrawArrays = (PROC_glDrawArrays)LoadMethod(PREFIX "glDrawArrays");
	this->DrawElements = (PROC_glDrawElements)LoadMethod(PREFIX "glDrawElements");
	this->GetPointerv = (PROC_glGetPointerv)LoadMethod(PREFIX "glGetPointerv");
	this->PolygonOffset = (PROC_glPolygonOffset)LoadMethod(PREFIX "glPolygonOffset");
	this->CopyTexImage1D = (PROC_glCopyTexImage1D)LoadMethod(PREFIX "glCopyTexImage1D");
	this->CopyTexImage2D = (PROC_glCopyTexImage2D)LoadMethod(PREFIX "glCopyTexImage2D");
	this->CopyTexSubImage1D = (PROC_glCopyTexSubImage1D)LoadMethod(PREFIX "glCopyTexSubImage1D");
	this->CopyTexSubImage2D = (PROC_glCopyTexSubImage2D)LoadMethod(PREFIX "glCopyTexSubImage2D");
	this->TexSubImage1D = (PROC_glTexSubImage1D)LoadMethod(PREFIX "glTexSubImage1D");
	this->TexSubImage2D = (PROC_glTexSubImage2D)LoadMethod(PREFIX "glTexSubImage2D");
	this->BindTexture = (PROC_glBindTexture)LoadMethod(PREFIX "glBindTexture");
	this->DeleteTextures = (PROC_glDeleteTextures)LoadMethod(PREFIX "glDeleteTextures");
	this->GenTextures = (PROC_glGenTextures)LoadMethod(PREFIX "glGenTextures");
	this->IsTexture = (PROC_glIsTexture)LoadMethod(PREFIX "glIsTexture");
	this->DrawRangeElements = (PROC_glDrawRangeElements)LoadMethod(PREFIX "glDrawRangeElements");
	this->TexImage3D = (PROC_glTexImage3D)LoadMethod(PREFIX "glTexImage3D");
	this->TexSubImage3D = (PROC_glTexSubImage3D)LoadMethod(PREFIX "glTexSubImage3D");
	this->CopyTexSubImage3D = (PROC_glCopyTexSubImage3D)LoadMethod(PREFIX "glCopyTexSubImage3D");
	this->ActiveTexture = (PROC_glActiveTexture)LoadMethod(PREFIX "glActiveTexture");
	this->SampleCoverage = (PROC_glSampleCoverage)LoadMethod(PREFIX "glSampleCoverage");
	this->CompressedTexImage3D = (PROC_glCompressedTexImage3D)LoadMethod(PREFIX "glCompressedTexImage3D");
	this->CompressedTexImage2D = (PROC_glCompressedTexImage2D)LoadMethod(PREFIX "glCompressedTexImage2D");
	this->CompressedTexImage1D = (PROC_glCompressedTexImage1D)LoadMethod(PREFIX "glCompressedTexImage1D");
	this->CompressedTexSubImage3D = (PROC_glCompressedTexSubImage3D)LoadMethod(PREFIX "glCompressedTexSubImage3D");
	this->CompressedTexSubImage2D = (PROC_glCompressedTexSubImage2D)LoadMethod(PREFIX "glCompressedTexSubImage2D");
	this->CompressedTexSubImage1D = (PROC_glCompressedTexSubImage1D)LoadMethod(PREFIX "glCompressedTexSubImage1D");
	this->GetCompressedTexImage = (PROC_glGetCompressedTexImage)LoadMethod(PREFIX "glGetCompressedTexImage");
	this->BlendFuncSeparate = (PROC_glBlendFuncSeparate)LoadMethod(PREFIX "glBlendFuncSeparate");
	this->MultiDrawArrays = (PROC_glMultiDrawArrays)LoadMethod(PREFIX "glMultiDrawArrays");
	this->MultiDrawElements = (PROC_glMultiDrawElements)LoadMethod(PREFIX "glMultiDrawElements");
	this->PointParameterf = (PROC_glPointParameterf)LoadMethod(PREFIX "glPointParameterf");
	this->PointParameterfv = (PROC_glPointParameterfv)LoadMethod(PREFIX "glPointParameterfv");
	this->PointParameteri = (PROC_glPointParameteri)LoadMethod(PREFIX "glPointParameteri");
	this->PointParameteriv = (PROC_glPointParameteriv)LoadMethod(PREFIX "glPointParameteriv");
	this->BlendColor = (PROC_glBlendColor)LoadMethod(PREFIX "glBlendColor");
	this->BlendEquation = (PROC_glBlendEquation)LoadMethod(PREFIX "glBlendEquation");
	this->GenQueries = (PROC_glGenQueries)LoadMethod(PREFIX "glGenQueries");
	this->DeleteQueries = (PROC_glDeleteQueries)LoadMethod(PREFIX "glDeleteQueries");
	this->IsQuery = (PROC_glIsQuery)LoadMethod(PREFIX "glIsQuery");
	this->BeginQuery = (PROC_glBeginQuery)LoadMethod(PREFIX "glBeginQuery");
	this->EndQuery = (PROC_glEndQuery)LoadMethod(PREFIX "glEndQuery");
	this->GetQueryiv = (PROC_glGetQueryiv)LoadMethod(PREFIX "glGetQueryiv");
	this->GetQueryObjectiv = (PROC_glGetQueryObjectiv)LoadMethod(PREFIX "glGetQueryObjectiv");
	this->GetQueryObjectuiv = (PROC_glGetQueryObjectuiv)LoadMethod(PREFIX "glGetQueryObjectuiv");
	this->BindBuffer = (PROC_glBindBuffer)LoadMethod(PREFIX "glBindBuffer");
	this->DeleteBuffers = (PROC_glDeleteBuffers)LoadMethod(PREFIX "glDeleteBuffers");
	this->GenBuffers = (PROC_glGenBuffers)LoadMethod(PREFIX "glGenBuffers");
	this->IsBuffer = (PROC_glIsBuffer)LoadMethod(PREFIX "glIsBuffer");
	this->BufferData = (PROC_glBufferData)LoadMethod(PREFIX "glBufferData");
	this->BufferSubData = (PROC_glBufferSubData)LoadMethod(PREFIX "glBufferSubData");
	this->GetBufferSubData = (PROC_glGetBufferSubData)LoadMethod(PREFIX "glGetBufferSubData");
	this->MapBuffer = (PROC_glMapBuffer)LoadMethod(PREFIX "glMapBuffer");
	this->UnmapBuffer = (PROC_glUnmapBuffer)LoadMethod(PREFIX "glUnmapBuffer");
	this->GetBufferParameteriv = (PROC_glGetBufferParameteriv)LoadMethod(PREFIX "glGetBufferParameteriv");
	this->GetBufferPointerv = (PROC_glGetBufferPointerv)LoadMethod(PREFIX "glGetBufferPointerv");
	this->BlendEquationSeparate = (PROC_glBlendEquationSeparate)LoadMethod(PREFIX "glBlendEquationSeparate");
	this->DrawBuffers = (PROC_glDrawBuffers)LoadMethod(PREFIX "glDrawBuffers");
	this->StencilOpSeparate = (PROC_glStencilOpSeparate)LoadMethod(PREFIX "glStencilOpSeparate");
	this->StencilFuncSeparate = (PROC_glStencilFuncSeparate)LoadMethod(PREFIX "glStencilFuncSeparate");
	this->StencilMaskSeparate = (PROC_glStencilMaskSeparate)LoadMethod(PREFIX "glStencilMaskSeparate");
	this->AttachShader = (PROC_glAttachShader)LoadMethod(PREFIX "glAttachShader");
	this->BindAttribLocation = (PROC_glBindAttribLocation)LoadMethod(PREFIX "glBindAttribLocation");
	this->CompileShader = (PROC_glCompileShader)LoadMethod(PREFIX "glCompileShader");
	this->CreateProgram = (PROC_glCreateProgram)LoadMethod(PREFIX "glCreateProgram");
	this->CreateShader = (PROC_glCreateShader)LoadMethod(PREFIX "glCreateShader");
	this->DeleteProgram = (PROC_glDeleteProgram)LoadMethod(PREFIX "glDeleteProgram");
	this->DeleteShader = (PROC_glDeleteShader)LoadMethod(PREFIX "glDeleteShader");
	this->DetachShader = (PROC_glDetachShader)LoadMethod(PREFIX "glDetachShader");
	this->DisableVertexAttribArray = (PROC_glDisableVertexAttribArray)LoadMethod(PREFIX "glDisableVertexAttribArray");
	this->EnableVertexAttribArray = (PROC_glEnableVertexAttribArray)LoadMethod(PREFIX "glEnableVertexAttribArray");
	this->GetActiveAttrib = (PROC_glGetActiveAttrib)LoadMethod(PREFIX "glGetActiveAttrib");
	this->GetActiveUniform = (PROC_glGetActiveUniform)LoadMethod(PREFIX "glGetActiveUniform");
	this->GetAttachedShaders = (PROC_glGetAttachedShaders)LoadMethod(PREFIX "glGetAttachedShaders");
	this->GetAttribLocation = (PROC_glGetAttribLocation)LoadMethod(PREFIX "glGetAttribLocation");
	this->GetProgramiv = (PROC_glGetProgramiv)LoadMethod(PREFIX "glGetProgramiv");
	this->GetProgramInfoLog = (PROC_glGetProgramInfoLog)LoadMethod(PREFIX "glGetProgramInfoLog");
	this->GetShaderiv = (PROC_glGetShaderiv)LoadMethod(PREFIX "glGetShaderiv");
	this->GetShaderInfoLog = (PROC_glGetShaderInfoLog)LoadMethod(PREFIX "glGetShaderInfoLog");
	this->GetShaderSource = (PROC_glGetShaderSource)LoadMethod(PREFIX "glGetShaderSource");
	this->GetUniformLocation = (PROC_glGetUniformLocation)LoadMethod(PREFIX "glGetUniformLocation");
	this->GetUniformfv = (PROC_glGetUniformfv)LoadMethod(PREFIX "glGetUniformfv");
	this->GetUniformiv = (PROC_glGetUniformiv)LoadMethod(PREFIX "glGetUniformiv");
	this->GetVertexAttribdv = (PROC_glGetVertexAttribdv)LoadMethod(PREFIX "glGetVertexAttribdv");
	this->GetVertexAttribfv = (PROC_glGetVertexAttribfv)LoadMethod(PREFIX "glGetVertexAttribfv");
	this->GetVertexAttribiv = (PROC_glGetVertexAttribiv)LoadMethod(PREFIX "glGetVertexAttribiv");
	this->GetVertexAttribPointerv = (PROC_glGetVertexAttribPointerv)LoadMethod(PREFIX "glGetVertexAttribPointerv");
	this->IsProgram = (PROC_glIsProgram)LoadMethod(PREFIX "glIsProgram");
	this->IsShader = (PROC_glIsShader)LoadMethod(PREFIX "glIsShader");
	this->LinkProgram = (PROC_glLinkProgram)LoadMethod(PREFIX "glLinkProgram");
	this->ShaderSource = (PROC_glShaderSource)LoadMethod(PREFIX "glShaderSource");
	this->UseProgram = (PROC_glUseProgram)LoadMethod(PREFIX "glUseProgram");
	this->Uniform1f = (PROC_glUniform1f)LoadMethod(PREFIX "glUniform1f");
	this->Uniform2f = (PROC_glUniform2f)LoadMethod(PREFIX "glUniform2f");
	this->Uniform3f = (PROC_glUniform3f)LoadMethod(PREFIX "glUniform3f");
	this->Uniform4f = (PROC_glUniform4f)LoadMethod(PREFIX "glUniform4f");
	this->Uniform1i = (PROC_glUniform1i)LoadMethod(PREFIX "glUniform1i");
	this->Uniform2i = (PROC_glUniform2i)LoadMethod(PREFIX "glUniform2i");
	this->Uniform3i = (PROC_glUniform3i)LoadMethod(PREFIX "glUniform3i");
	this->Uniform4i = (PROC_glUniform4i)LoadMethod(PREFIX "glUniform4i");
	this->Uniform1fv = (PROC_glUniform1fv)LoadMethod(PREFIX "glUniform1fv");
	this->Uniform2fv = (PROC_glUniform2fv)LoadMethod(PREFIX "glUniform2fv");
	this->Uniform3fv = (PROC_glUniform3fv)LoadMethod(PREFIX "glUniform3fv");
	this->Uniform4fv = (PROC_glUniform4fv)LoadMethod(PREFIX "glUniform4fv");
	this->Uniform1iv = (PROC_glUniform1iv)LoadMethod(PREFIX "glUniform1iv");
	this->Uniform2iv = (PROC_glUniform2iv)LoadMethod(PREFIX "glUniform2iv");
	this->Uniform3iv = (PROC_glUniform3iv)LoadMethod(PREFIX "glUniform3iv");
	this->Uniform4iv = (PROC_glUniform4iv)LoadMethod(PREFIX "glUniform4iv");
	this->UniformMatrix2fv = (PROC_glUniformMatrix2fv)LoadMethod(PREFIX "glUniformMatrix2fv");
	this->UniformMatrix3fv = (PROC_glUniformMatrix3fv)LoadMethod(PREFIX "glUniformMatrix3fv");
	this->UniformMatrix4fv = (PROC_glUniformMatrix4fv)LoadMethod(PREFIX "glUniformMatrix4fv");
	this->ValidateProgram = (PROC_glValidateProgram)LoadMethod(PREFIX "glValidateProgram");
	this->VertexAttrib1d = (PROC_glVertexAttrib1d)LoadMethod(PREFIX "glVertexAttrib1d");
	this->VertexAttrib1dv = (PROC_glVertexAttrib1dv)LoadMethod(PREFIX "glVertexAttrib1dv");
	this->VertexAttrib1f = (PROC_glVertexAttrib1f)LoadMethod(PREFIX "glVertexAttrib1f");
	this->VertexAttrib1fv = (PROC_glVertexAttrib1fv)LoadMethod(PREFIX "glVertexAttrib1fv");
	this->VertexAttrib1s = (PROC_glVertexAttrib1s)LoadMethod(PREFIX "glVertexAttrib1s");
	this->VertexAttrib1sv = (PROC_glVertexAttrib1sv)LoadMethod(PREFIX "glVertexAttrib1sv");
	this->VertexAttrib2d = (PROC_glVertexAttrib2d)LoadMethod(PREFIX "glVertexAttrib2d");
	this->VertexAttrib2dv = (PROC_glVertexAttrib2dv)LoadMethod(PREFIX "glVertexAttrib2dv");
	this->VertexAttrib2f = (PROC_glVertexAttrib2f)LoadMethod(PREFIX "glVertexAttrib2f");
	this->VertexAttrib2fv = (PROC_glVertexAttrib2fv)LoadMethod(PREFIX "glVertexAttrib2fv");
	this->VertexAttrib2s = (PROC_glVertexAttrib2s)LoadMethod(PREFIX "glVertexAttrib2s");
	this->VertexAttrib2sv = (PROC_glVertexAttrib2sv)LoadMethod(PREFIX "glVertexAttrib2sv");
	this->VertexAttrib3d = (PROC_glVertexAttrib3d)LoadMethod(PREFIX "glVertexAttrib3d");
	this->VertexAttrib3dv = (PROC_glVertexAttrib3dv)LoadMethod(PREFIX "glVertexAttrib3dv");
	this->VertexAttrib3f = (PROC_glVertexAttrib3f)LoadMethod(PREFIX "glVertexAttrib3f");
	this->VertexAttrib3fv = (PROC_glVertexAttrib3fv)LoadMethod(PREFIX "glVertexAttrib3fv");
	this->VertexAttrib3s = (PROC_glVertexAttrib3s)LoadMethod(PREFIX "glVertexAttrib3s");
	this->VertexAttrib3sv = (PROC_glVertexAttrib3sv)LoadMethod(PREFIX "glVertexAttrib3sv");
	this->VertexAttrib4Nbv = (PROC_glVertexAttrib4Nbv)LoadMethod(PREFIX "glVertexAttrib4Nbv");
	this->VertexAttrib4Niv = (PROC_glVertexAttrib4Niv)LoadMethod(PREFIX "glVertexAttrib4Niv");
	this->VertexAttrib4Nsv = (PROC_glVertexAttrib4Nsv)LoadMethod(PREFIX "glVertexAttrib4Nsv");
	this->VertexAttrib4Nub = (PROC_glVertexAttrib4Nub)LoadMethod(PREFIX "glVertexAttrib4Nub");
	this->VertexAttrib4Nubv = (PROC_glVertexAttrib4Nubv)LoadMethod(PREFIX "glVertexAttrib4Nubv");
	this->VertexAttrib4Nuiv = (PROC_glVertexAttrib4Nuiv)LoadMethod(PREFIX "glVertexAttrib4Nuiv");
	this->VertexAttrib4Nusv = (PROC_glVertexAttrib4Nusv)LoadMethod(PREFIX "glVertexAttrib4Nusv");
	this->VertexAttrib4bv = (PROC_glVertexAttrib4bv)LoadMethod(PREFIX "glVertexAttrib4bv");
	this->VertexAttrib4d = (PROC_glVertexAttrib4d)LoadMethod(PREFIX "glVertexAttrib4d");
	this->VertexAttrib4dv = (PROC_glVertexAttrib4dv)LoadMethod(PREFIX "glVertexAttrib4dv");
	this->VertexAttrib4f = (PROC_glVertexAttrib4f)LoadMethod(PREFIX "glVertexAttrib4f");
	this->VertexAttrib4fv = (PROC_glVertexAttrib4fv)LoadMethod(PREFIX "glVertexAttrib4fv");
	this->VertexAttrib4iv = (PROC_glVertexAttrib4iv)LoadMethod(PREFIX "glVertexAttrib4iv");
	this->VertexAttrib4s = (PROC_glVertexAttrib4s)LoadMethod(PREFIX "glVertexAttrib4s");
	this->VertexAttrib4sv = (PROC_glVertexAttrib4sv)LoadMethod(PREFIX "glVertexAttrib4sv");
	this->VertexAttrib4ubv = (PROC_glVertexAttrib4ubv)LoadMethod(PREFIX "glVertexAttrib4ubv");
	this->VertexAttrib4uiv = (PROC_glVertexAttrib4uiv)LoadMethod(PREFIX "glVertexAttrib4uiv");
	this->VertexAttrib4usv = (PROC_glVertexAttrib4usv)LoadMethod(PREFIX "glVertexAttrib4usv");
	this->VertexAttribPointer = (PROC_glVertexAttribPointer)LoadMethod(PREFIX "glVertexAttribPointer");
	this->UniformMatrix2x3fv = (PROC_glUniformMatrix2x3fv)LoadMethod(PREFIX "glUniformMatrix2x3fv");
	this->UniformMatrix3x2fv = (PROC_glUniformMatrix3x2fv)LoadMethod(PREFIX "glUniformMatrix3x2fv");
	this->UniformMatrix2x4fv = (PROC_glUniformMatrix2x4fv)LoadMethod(PREFIX "glUniformMatrix2x4fv");
	this->UniformMatrix4x2fv = (PROC_glUniformMatrix4x2fv)LoadMethod(PREFIX "glUniformMatrix4x2fv");
	this->UniformMatrix3x4fv = (PROC_glUniformMatrix3x4fv)LoadMethod(PREFIX "glUniformMatrix3x4fv");
	this->UniformMatrix4x3fv = (PROC_glUniformMatrix4x3fv)LoadMethod(PREFIX "glUniformMatrix4x3fv");
	this->ColorMaski = (PROC_glColorMaski)LoadMethod(PREFIX "glColorMaski");
	this->GetBooleani_v = (PROC_glGetBooleani_v)LoadMethod(PREFIX "glGetBooleani_v");
	this->GetIntegeri_v = (PROC_glGetIntegeri_v)LoadMethod(PREFIX "glGetIntegeri_v");
	this->Enablei = (PROC_glEnablei)LoadMethod(PREFIX "glEnablei");
	this->Disablei = (PROC_glDisablei)LoadMethod(PREFIX "glDisablei");
	this->IsEnabledi = (PROC_glIsEnabledi)LoadMethod(PREFIX "glIsEnabledi");
	this->BeginTransformFeedback = (PROC_glBeginTransformFeedback)LoadMethod(PREFIX "glBeginTransformFeedback");
	this->EndTransformFeedback = (PROC_glEndTransformFeedback)LoadMethod(PREFIX "glEndTransformFeedback");
	this->BindBufferRange = (PROC_glBindBufferRange)LoadMethod(PREFIX "glBindBufferRange");
	this->BindBufferBase = (PROC_glBindBufferBase)LoadMethod(PREFIX "glBindBufferBase");
	this->TransformFeedbackVaryings = (PROC_glTransformFeedbackVaryings)LoadMethod(PREFIX "glTransformFeedbackVaryings");
	this->GetTransformFeedbackVarying = (PROC_glGetTransformFeedbackVarying)LoadMethod(PREFIX "glGetTransformFeedbackVarying");
	this->ClampColor = (PROC_glClampColor)LoadMethod(PREFIX "glClampColor");
	this->BeginConditionalRender = (PROC_glBeginConditionalRender)LoadMethod(PREFIX "glBeginConditionalRender");
	this->EndConditionalRender = (PROC_glEndConditionalRender)LoadMethod(PREFIX "glEndConditionalRender");
	this->VertexAttribIPointer = (PROC_glVertexAttribIPointer)LoadMethod(PREFIX "glVertexAttribIPointer");
	this->GetVertexAttribIiv = (PROC_glGetVertexAttribIiv)LoadMethod(PREFIX "glGetVertexAttribIiv");
	this->GetVertexAttribIuiv = (PROC_glGetVertexAttribIuiv)LoadMethod(PREFIX "glGetVertexAttribIuiv");
	this->VertexAttribI1i = (PROC_glVertexAttribI1i)LoadMethod(PREFIX "glVertexAttribI1i");
	this->VertexAttribI2i = (PROC_glVertexAttribI2i)LoadMethod(PREFIX "glVertexAttribI2i");
	this->VertexAttribI3i = (PROC_glVertexAttribI3i)LoadMethod(PREFIX "glVertexAttribI3i");
	this->VertexAttribI4i = (PROC_glVertexAttribI4i)LoadMethod(PREFIX "glVertexAttribI4i");
	this->VertexAttribI1ui = (PROC_glVertexAttribI1ui)LoadMethod(PREFIX "glVertexAttribI1ui");
	this->VertexAttribI2ui = (PROC_glVertexAttribI2ui)LoadMethod(PREFIX "glVertexAttribI2ui");
	this->VertexAttribI3ui = (PROC_glVertexAttribI3ui)LoadMethod(PREFIX "glVertexAttribI3ui");
	this->VertexAttribI4ui = (PROC_glVertexAttribI4ui)LoadMethod(PREFIX "glVertexAttribI4ui");
	this->VertexAttribI1iv = (PROC_glVertexAttribI1iv)LoadMethod(PREFIX "glVertexAttribI1iv");
	this->VertexAttribI2iv = (PROC_glVertexAttribI2iv)LoadMethod(PREFIX "glVertexAttribI2iv");
	this->VertexAttribI3iv = (PROC_glVertexAttribI3iv)LoadMethod(PREFIX "glVertexAttribI3iv");
	this->VertexAttribI4iv = (PROC_glVertexAttribI4iv)LoadMethod(PREFIX "glVertexAttribI4iv");
	this->VertexAttribI1uiv = (PROC_glVertexAttribI1uiv)LoadMethod(PREFIX "glVertexAttribI1uiv");
	this->VertexAttribI2uiv = (PROC_glVertexAttribI2uiv)LoadMethod(PREFIX "glVertexAttribI2uiv");
	this->VertexAttribI3uiv = (PROC_glVertexAttribI3uiv)LoadMethod(PREFIX "glVertexAttribI3uiv");
	this->VertexAttribI4uiv = (PROC_glVertexAttribI4uiv)LoadMethod(PREFIX "glVertexAttribI4uiv");
	this->VertexAttribI4bv = (PROC_glVertexAttribI4bv)LoadMethod(PREFIX "glVertexAttribI4bv");
	this->VertexAttribI4sv = (PROC_glVertexAttribI4sv)LoadMethod(PREFIX "glVertexAttribI4sv");
	this->VertexAttribI4ubv = (PROC_glVertexAttribI4ubv)LoadMethod(PREFIX "glVertexAttribI4ubv");
	this->VertexAttribI4usv = (PROC_glVertexAttribI4usv)LoadMethod(PREFIX "glVertexAttribI4usv");
	this->GetUniformuiv = (PROC_glGetUniformuiv)LoadMethod(PREFIX "glGetUniformuiv");
	this->BindFragDataLocation = (PROC_glBindFragDataLocation)LoadMethod(PREFIX "glBindFragDataLocation");
	this->GetFragDataLocation = (PROC_glGetFragDataLocation)LoadMethod(PREFIX "glGetFragDataLocation");
	this->Uniform1ui = (PROC_glUniform1ui)LoadMethod(PREFIX "glUniform1ui");
	this->Uniform2ui = (PROC_glUniform2ui)LoadMethod(PREFIX "glUniform2ui");
	this->Uniform3ui = (PROC_glUniform3ui)LoadMethod(PREFIX "glUniform3ui");
	this->Uniform4ui = (PROC_glUniform4ui)LoadMethod(PREFIX "glUniform4ui");
	this->Uniform1uiv = (PROC_glUniform1uiv)LoadMethod(PREFIX "glUniform1uiv");
	this->Uniform2uiv = (PROC_glUniform2uiv)LoadMethod(PREFIX "glUniform2uiv");
	this->Uniform3uiv = (PROC_glUniform3uiv)LoadMethod(PREFIX "glUniform3uiv");
	this->Uniform4uiv = (PROC_glUniform4uiv)LoadMethod(PREFIX "glUniform4uiv");
	this->TexParameterIiv = (PROC_glTexParameterIiv)LoadMethod(PREFIX "glTexParameterIiv");
	this->TexParameterIuiv = (PROC_glTexParameterIuiv)LoadMethod(PREFIX "glTexParameterIuiv");
	this->GetTexParameterIiv = (PROC_glGetTexParameterIiv)LoadMethod(PREFIX "glGetTexParameterIiv");
	this->GetTexParameterIuiv = (PROC_glGetTexParameterIuiv)LoadMethod(PREFIX "glGetTexParameterIuiv");
	this->ClearBufferiv = (PROC_glClearBufferiv)LoadMethod(PREFIX "glClearBufferiv");
	this->ClearBufferuiv = (PROC_glClearBufferuiv)LoadMethod(PREFIX "glClearBufferuiv");
	this->ClearBufferfv = (PROC_glClearBufferfv)LoadMethod(PREFIX "glClearBufferfv");
	this->ClearBufferfi = (PROC_glClearBufferfi)LoadMethod(PREFIX "glClearBufferfi");
	this->GetStringi = (PROC_glGetStringi)LoadMethod(PREFIX "glGetStringi");
	this->IsRenderbuffer = (PROC_glIsRenderbuffer)LoadMethod(PREFIX "glIsRenderbuffer");
	this->BindRenderbuffer = (PROC_glBindRenderbuffer)LoadMethod(PREFIX "glBindRenderbuffer");
	this->DeleteRenderbuffers = (PROC_glDeleteRenderbuffers)LoadMethod(PREFIX "glDeleteRenderbuffers");
	this->GenRenderbuffers = (PROC_glGenRenderbuffers)LoadMethod(PREFIX "glGenRenderbuffers");
	this->RenderbufferStorage = (PROC_glRenderbufferStorage)LoadMethod(PREFIX "glRenderbufferStorage");
	this->GetRenderbufferParameteriv = (PROC_glGetRenderbufferParameteriv)LoadMethod(PREFIX "glGetRenderbufferParameteriv");
	this->IsFramebuffer = (PROC_glIsFramebuffer)LoadMethod(PREFIX "glIsFramebuffer");
	this->BindFramebuffer = (PROC_glBindFramebuffer)LoadMethod(PREFIX "glBindFramebuffer");
	this->DeleteFramebuffers = (PROC_glDeleteFramebuffers)LoadMethod(PREFIX "glDeleteFramebuffers");
	this->GenFramebuffers = (PROC_glGenFramebuffers)LoadMethod(PREFIX "glGenFramebuffers");
	this->CheckFramebufferStatus = (PROC_glCheckFramebufferStatus)LoadMethod(PREFIX "glCheckFramebufferStatus");
	this->FramebufferTexture1D = (PROC_glFramebufferTexture1D)LoadMethod(PREFIX "glFramebufferTexture1D");
	this->FramebufferTexture2D = (PROC_glFramebufferTexture2D)LoadMethod(PREFIX "glFramebufferTexture2D");
	this->FramebufferTexture3D = (PROC_glFramebufferTexture3D)LoadMethod(PREFIX "glFramebufferTexture3D");
	this->FramebufferRenderbuffer = (PROC_glFramebufferRenderbuffer)LoadMethod(PREFIX "glFramebufferRenderbuffer");
	this->GetFramebufferAttachmentParameteriv = (PROC_glGetFramebufferAttachmentParameteriv)LoadMethod(PREFIX "glGetFramebufferAttachmentParameteriv");
	this->GenerateMipmap = (PROC_glGenerateMipmap)LoadMethod(PREFIX "glGenerateMipmap");
	this->BlitFramebuffer = (PROC_glBlitFramebuffer)LoadMethod(PREFIX "glBlitFramebuffer");
	this->RenderbufferStorageMultisample = (PROC_glRenderbufferStorageMultisample)LoadMethod(PREFIX "glRenderbufferStorageMultisample");
	this->FramebufferTextureLayer = (PROC_glFramebufferTextureLayer)LoadMethod(PREFIX "glFramebufferTextureLayer");
	this->MapBufferRange = (PROC_glMapBufferRange)LoadMethod(PREFIX "glMapBufferRange");
	this->FlushMappedBufferRange = (PROC_glFlushMappedBufferRange)LoadMethod(PREFIX "glFlushMappedBufferRange");
	this->BindVertexArray = (PROC_glBindVertexArray)LoadMethod(PREFIX "glBindVertexArray");
	this->DeleteVertexArrays = (PROC_glDeleteVertexArrays)LoadMethod(PREFIX "glDeleteVertexArrays");
	this->GenVertexArrays = (PROC_glGenVertexArrays)LoadMethod(PREFIX "glGenVertexArrays");
	this->IsVertexArray = (PROC_glIsVertexArray)LoadMethod(PREFIX "glIsVertexArray");
	this->DrawArraysInstanced = (PROC_glDrawArraysInstanced)LoadMethod(PREFIX "glDrawArraysInstanced");
	this->DrawElementsInstanced = (PROC_glDrawElementsInstanced)LoadMethod(PREFIX "glDrawElementsInstanced");
	this->TexBuffer = (PROC_glTexBuffer)LoadMethod(PREFIX "glTexBuffer");
	this->PrimitiveRestartIndex = (PROC_glPrimitiveRestartIndex)LoadMethod(PREFIX "glPrimitiveRestartIndex");
	this->CopyBufferSubData = (PROC_glCopyBufferSubData)LoadMethod(PREFIX "glCopyBufferSubData");
	this->GetUniformIndices = (PROC_glGetUniformIndices)LoadMethod(PREFIX "glGetUniformIndices");
	this->GetActiveUniformsiv = (PROC_glGetActiveUniformsiv)LoadMethod(PREFIX "glGetActiveUniformsiv");
	this->GetActiveUniformName = (PROC_glGetActiveUniformName)LoadMethod(PREFIX "glGetActiveUniformName");
	this->GetUniformBlockIndex = (PROC_glGetUniformBlockIndex)LoadMethod(PREFIX "glGetUniformBlockIndex");
	this->GetActiveUniformBlockiv = (PROC_glGetActiveUniformBlockiv)LoadMethod(PREFIX "glGetActiveUniformBlockiv");
	this->GetActiveUniformBlockName = (PROC_glGetActiveUniformBlockName)LoadMethod(PREFIX "glGetActiveUniformBlockName");
	this->UniformBlockBinding = (PROC_glUniformBlockBinding)LoadMethod(PREFIX "glUniformBlockBinding");
	this->DrawElementsBaseVertex = (PROC_glDrawElementsBaseVertex)LoadMethod(PREFIX "glDrawElementsBaseVertex");
	this->DrawRangeElementsBaseVertex = (PROC_glDrawRangeElementsBaseVertex)LoadMethod(PREFIX "glDrawRangeElementsBaseVertex");
	this->DrawElementsInstancedBaseVertex = (PROC_glDrawElementsInstancedBaseVertex)LoadMethod(PREFIX "glDrawElementsInstancedBaseVertex");
	this->MultiDrawElementsBaseVertex = (PROC_glMultiDrawElementsBaseVertex)LoadMethod(PREFIX "glMultiDrawElementsBaseVertex");
	this->ProvokingVertex = (PROC_glProvokingVertex)LoadMethod(PREFIX "glProvokingVertex");
	this->FenceSync = (PROC_glFenceSync)LoadMethod(PREFIX "glFenceSync");
	this->IsSync = (PROC_glIsSync)LoadMethod(PREFIX "glIsSync");
	this->DeleteSync = (PROC_glDeleteSync)LoadMethod(PREFIX "glDeleteSync");
	this->ClientWaitSync = (PROC_glClientWaitSync)LoadMethod(PREFIX "glClientWaitSync");
	this->WaitSync = (PROC_glWaitSync)LoadMethod(PREFIX "glWaitSync");
	this->GetInteger64v = (PROC_glGetInteger64v)LoadMethod(PREFIX "glGetInteger64v");
	this->GetSynciv = (PROC_glGetSynciv)LoadMethod(PREFIX "glGetSynciv");
	this->GetInteger64i_v = (PROC_glGetInteger64i_v)LoadMethod(PREFIX "glGetInteger64i_v");
	this->GetBufferParameteri64v = (PROC_glGetBufferParameteri64v)LoadMethod(PREFIX "glGetBufferParameteri64v");
	this->FramebufferTexture = (PROC_glFramebufferTexture)LoadMethod(PREFIX "glFramebufferTexture");
	this->TexImage2DMultisample = (PROC_glTexImage2DMultisample)LoadMethod(PREFIX "glTexImage2DMultisample");
	this->TexImage3DMultisample = (PROC_glTexImage3DMultisample)LoadMethod(PREFIX "glTexImage3DMultisample");
	this->GetMultisamplefv = (PROC_glGetMultisamplefv)LoadMethod(PREFIX "glGetMultisamplefv");
	this->SampleMaski = (PROC_glSampleMaski)LoadMethod(PREFIX "glSampleMaski");
	this->BindFragDataLocationIndexed = (PROC_glBindFragDataLocationIndexed)LoadMethod(PREFIX "glBindFragDataLocationIndexed");
	this->GetFragDataIndex = (PROC_glGetFragDataIndex)LoadMethod(PREFIX "glGetFragDataIndex");
	this->GenSamplers = (PROC_glGenSamplers)LoadMethod(PREFIX "glGenSamplers");
	this->DeleteSamplers = (PROC_glDeleteSamplers)LoadMethod(PREFIX "glDeleteSamplers");
	this->IsSampler = (PROC_glIsSampler)LoadMethod(PREFIX "glIsSampler");
	this->BindSampler = (PROC_glBindSampler)LoadMethod(PREFIX "glBindSampler");
	this->SamplerParameteri = (PROC_glSamplerParameteri)LoadMethod(PREFIX "glSamplerParameteri");
	this->SamplerParameteriv = (PROC_glSamplerParameteriv)LoadMethod(PREFIX "glSamplerParameteriv");
	this->SamplerParameterf = (PROC_glSamplerParameterf)LoadMethod(PREFIX "glSamplerParameterf");
	this->SamplerParameterfv = (PROC_glSamplerParameterfv)LoadMethod(PREFIX "glSamplerParameterfv");
	this->SamplerParameterIiv = (PROC_glSamplerParameterIiv)LoadMethod(PREFIX "glSamplerParameterIiv");
	this->SamplerParameterIuiv = (PROC_glSamplerParameterIuiv)LoadMethod(PREFIX "glSamplerParameterIuiv");
	this->GetSamplerParameteriv = (PROC_glGetSamplerParameteriv)LoadMethod(PREFIX "glGetSamplerParameteriv");
	this->GetSamplerParameterIiv = (PROC_glGetSamplerParameterIiv)LoadMethod(PREFIX "glGetSamplerParameterIiv");
	this->GetSamplerParameterfv = (PROC_glGetSamplerParameterfv)LoadMethod(PREFIX "glGetSamplerParameterfv");
	this->GetSamplerParameterIuiv = (PROC_glGetSamplerParameterIuiv)LoadMethod(PREFIX "glGetSamplerParameterIuiv");
	this->QueryCounter = (PROC_glQueryCounter)LoadMethod(PREFIX "glQueryCounter");
	this->GetQueryObjecti64v = (PROC_glGetQueryObjecti64v)LoadMethod(PREFIX "glGetQueryObjecti64v");
	this->GetQueryObjectui64v = (PROC_glGetQueryObjectui64v)LoadMethod(PREFIX "glGetQueryObjectui64v");
	this->VertexAttribDivisor = (PROC_glVertexAttribDivisor)LoadMethod(PREFIX "glVertexAttribDivisor");
	this->VertexAttribP1ui = (PROC_glVertexAttribP1ui)LoadMethod(PREFIX "glVertexAttribP1ui");
	this->VertexAttribP1uiv = (PROC_glVertexAttribP1uiv)LoadMethod(PREFIX "glVertexAttribP1uiv");
	this->VertexAttribP2ui = (PROC_glVertexAttribP2ui)LoadMethod(PREFIX "glVertexAttribP2ui");
	this->VertexAttribP2uiv = (PROC_glVertexAttribP2uiv)LoadMethod(PREFIX "glVertexAttribP2uiv");
	this->VertexAttribP3ui = (PROC_glVertexAttribP3ui)LoadMethod(PREFIX "glVertexAttribP3ui");
	this->VertexAttribP3uiv = (PROC_glVertexAttribP3uiv)LoadMethod(PREFIX "glVertexAttribP3uiv");
	this->VertexAttribP4ui = (PROC_glVertexAttribP4ui)LoadMethod(PREFIX "glVertexAttribP4ui");
	this->VertexAttribP4uiv = (PROC_glVertexAttribP4uiv)LoadMethod(PREFIX "glVertexAttribP4uiv");
	this->MinSampleShading = (PROC_glMinSampleShading)LoadMethod(PREFIX "glMinSampleShading");
	this->BlendEquationi = (PROC_glBlendEquationi)LoadMethod(PREFIX "glBlendEquationi");
	this->BlendEquationSeparatei = (PROC_glBlendEquationSeparatei)LoadMethod(PREFIX "glBlendEquationSeparatei");
	this->BlendFunci = (PROC_glBlendFunci)LoadMethod(PREFIX "glBlendFunci");
	this->BlendFuncSeparatei = (PROC_glBlendFuncSeparatei)LoadMethod(PREFIX "glBlendFuncSeparatei");
	this->DrawArraysIndirect = (PROC_glDrawArraysIndirect)LoadMethod(PREFIX "glDrawArraysIndirect");
	this->DrawElementsIndirect = (PROC_glDrawElementsIndirect)LoadMethod(PREFIX "glDrawElementsIndirect");
	this->Uniform1d = (PROC_glUniform1d)LoadMethod(PREFIX "glUniform1d");
	this->Uniform2d = (PROC_glUniform2d)LoadMethod(PREFIX "glUniform2d");
	this->Uniform3d = (PROC_glUniform3d)LoadMethod(PREFIX "glUniform3d");
	this->Uniform4d = (PROC_glUniform4d)LoadMethod(PREFIX "glUniform4d");
	this->Uniform1dv = (PROC_glUniform1dv)LoadMethod(PREFIX "glUniform1dv");
	this->Uniform2dv = (PROC_glUniform2dv)LoadMethod(PREFIX "glUniform2dv");
	this->Uniform3dv = (PROC_glUniform3dv)LoadMethod(PREFIX "glUniform3dv");
	this->Uniform4dv = (PROC_glUniform4dv)LoadMethod(PREFIX "glUniform4dv");
	this->UniformMatrix2dv = (PROC_glUniformMatrix2dv)LoadMethod(PREFIX "glUniformMatrix2dv");
	this->UniformMatrix3dv = (PROC_glUniformMatrix3dv)LoadMethod(PREFIX "glUniformMatrix3dv");
	this->UniformMatrix4dv = (PROC_glUniformMatrix4dv)LoadMethod(PREFIX "glUniformMatrix4dv");
	this->UniformMatrix2x3dv = (PROC_glUniformMatrix2x3dv)LoadMethod(PREFIX "glUniformMatrix2x3dv");
	this->UniformMatrix2x4dv = (PROC_glUniformMatrix2x4dv)LoadMethod(PREFIX "glUniformMatrix2x4dv");
	this->UniformMatrix3x2dv = (PROC_glUniformMatrix3x2dv)LoadMethod(PREFIX "glUniformMatrix3x2dv");
	this->UniformMatrix3x4dv = (PROC_glUniformMatrix3x4dv)LoadMethod(PREFIX "glUniformMatrix3x4dv");
	this->UniformMatrix4x2dv = (PROC_glUniformMatrix4x2dv)LoadMethod(PREFIX "glUniformMatrix4x2dv");
	this->UniformMatrix4x3dv = (PROC_glUniformMatrix4x3dv)LoadMethod(PREFIX "glUniformMatrix4x3dv");
	this->GetUniformdv = (PROC_glGetUniformdv)LoadMethod(PREFIX "glGetUniformdv");
	this->GetSubroutineUniformLocation = (PROC_glGetSubroutineUniformLocation)LoadMethod(PREFIX "glGetSubroutineUniformLocation");
	this->GetSubroutineIndex = (PROC_glGetSubroutineIndex)LoadMethod(PREFIX "glGetSubroutineIndex");
	this->GetActiveSubroutineUniformiv = (PROC_glGetActiveSubroutineUniformiv)LoadMethod(PREFIX "glGetActiveSubroutineUniformiv");
	this->GetActiveSubroutineUniformName = (PROC_glGetActiveSubroutineUniformName)LoadMethod(PREFIX "glGetActiveSubroutineUniformName");
	this->GetActiveSubroutineName = (PROC_glGetActiveSubroutineName)LoadMethod(PREFIX "glGetActiveSubroutineName");
	this->UniformSubroutinesuiv = (PROC_glUniformSubroutinesuiv)LoadMethod(PREFIX "glUniformSubroutinesuiv");
	this->GetUniformSubroutineuiv = (PROC_glGetUniformSubroutineuiv)LoadMethod(PREFIX "glGetUniformSubroutineuiv");
	this->GetProgramStageiv = (PROC_glGetProgramStageiv)LoadMethod(PREFIX "glGetProgramStageiv");
	this->PatchParameteri = (PROC_glPatchParameteri)LoadMethod(PREFIX "glPatchParameteri");
	this->PatchParameterfv = (PROC_glPatchParameterfv)LoadMethod(PREFIX "glPatchParameterfv");
	this->BindTransformFeedback = (PROC_glBindTransformFeedback)LoadMethod(PREFIX "glBindTransformFeedback");
	this->DeleteTransformFeedbacks = (PROC_glDeleteTransformFeedbacks)LoadMethod(PREFIX "glDeleteTransformFeedbacks");
	this->GenTransformFeedbacks = (PROC_glGenTransformFeedbacks)LoadMethod(PREFIX "glGenTransformFeedbacks");
	this->IsTransformFeedback = (PROC_glIsTransformFeedback)LoadMethod(PREFIX "glIsTransformFeedback");
	this->PauseTransformFeedback = (PROC_glPauseTransformFeedback)LoadMethod(PREFIX "glPauseTransformFeedback");
	this->ResumeTransformFeedback = (PROC_glResumeTransformFeedback)LoadMethod(PREFIX "glResumeTransformFeedback");
	this->DrawTransformFeedback = (PROC_glDrawTransformFeedback)LoadMethod(PREFIX "glDrawTransformFeedback");
	this->DrawTransformFeedbackStream = (PROC_glDrawTransformFeedbackStream)LoadMethod(PREFIX "glDrawTransformFeedbackStream");
	this->BeginQueryIndexed = (PROC_glBeginQueryIndexed)LoadMethod(PREFIX "glBeginQueryIndexed");
	this->EndQueryIndexed = (PROC_glEndQueryIndexed)LoadMethod(PREFIX "glEndQueryIndexed");
	this->GetQueryIndexediv = (PROC_glGetQueryIndexediv)LoadMethod(PREFIX "glGetQueryIndexediv");
	this->ReleaseShaderCompiler = (PROC_glReleaseShaderCompiler)LoadMethod(PREFIX "glReleaseShaderCompiler");
	this->ShaderBinary = (PROC_glShaderBinary)LoadMethod(PREFIX "glShaderBinary");
	this->GetShaderPrecisionFormat = (PROC_glGetShaderPrecisionFormat)LoadMethod(PREFIX "glGetShaderPrecisionFormat");
	this->DepthRangef = (PROC_glDepthRangef)LoadMethod(PREFIX "glDepthRangef");
	this->ClearDepthf = (PROC_glClearDepthf)LoadMethod(PREFIX "glClearDepthf");
	this->GetProgramBinary = (PROC_glGetProgramBinary)LoadMethod(PREFIX "glGetProgramBinary");
	this->ProgramBinary = (PROC_glProgramBinary)LoadMethod(PREFIX "glProgramBinary");
	this->ProgramParameteri = (PROC_glProgramParameteri)LoadMethod(PREFIX "glProgramParameteri");
	this->UseProgramStages = (PROC_glUseProgramStages)LoadMethod(PREFIX "glUseProgramStages");
	this->ActiveShaderProgram = (PROC_glActiveShaderProgram)LoadMethod(PREFIX "glActiveShaderProgram");
	this->CreateShaderProgramv = (PROC_glCreateShaderProgramv)LoadMethod(PREFIX "glCreateShaderProgramv");
	this->BindProgramPipeline = (PROC_glBindProgramPipeline)LoadMethod(PREFIX "glBindProgramPipeline");
	this->DeleteProgramPipelines = (PROC_glDeleteProgramPipelines)LoadMethod(PREFIX "glDeleteProgramPipelines");
	this->GenProgramPipelines = (PROC_glGenProgramPipelines)LoadMethod(PREFIX "glGenProgramPipelines");
	this->IsProgramPipeline = (PROC_glIsProgramPipeline)LoadMethod(PREFIX "glIsProgramPipeline");
	this->GetProgramPipelineiv = (PROC_glGetProgramPipelineiv)LoadMethod(PREFIX "glGetProgramPipelineiv");
	this->ProgramUniform1i = (PROC_glProgramUniform1i)LoadMethod(PREFIX "glProgramUniform1i");
	this->ProgramUniform1iv = (PROC_glProgramUniform1iv)LoadMethod(PREFIX "glProgramUniform1iv");
	this->ProgramUniform1f = (PROC_glProgramUniform1f)LoadMethod(PREFIX "glProgramUniform1f");
	this->ProgramUniform1fv = (PROC_glProgramUniform1fv)LoadMethod(PREFIX "glProgramUniform1fv");
	this->ProgramUniform1d = (PROC_glProgramUniform1d)LoadMethod(PREFIX "glProgramUniform1d");
	this->ProgramUniform1dv = (PROC_glProgramUniform1dv)LoadMethod(PREFIX "glProgramUniform1dv");
	this->ProgramUniform1ui = (PROC_glProgramUniform1ui)LoadMethod(PREFIX "glProgramUniform1ui");
	this->ProgramUniform1uiv = (PROC_glProgramUniform1uiv)LoadMethod(PREFIX "glProgramUniform1uiv");
	this->ProgramUniform2i = (PROC_glProgramUniform2i)LoadMethod(PREFIX "glProgramUniform2i");
	this->ProgramUniform2iv = (PROC_glProgramUniform2iv)LoadMethod(PREFIX "glProgramUniform2iv");
	this->ProgramUniform2f = (PROC_glProgramUniform2f)LoadMethod(PREFIX "glProgramUniform2f");
	this->ProgramUniform2fv = (PROC_glProgramUniform2fv)LoadMethod(PREFIX "glProgramUniform2fv");
	this->ProgramUniform2d = (PROC_glProgramUniform2d)LoadMethod(PREFIX "glProgramUniform2d");
	this->ProgramUniform2dv = (PROC_glProgramUniform2dv)LoadMethod(PREFIX "glProgramUniform2dv");
	this->ProgramUniform2ui = (PROC_glProgramUniform2ui)LoadMethod(PREFIX "glProgramUniform2ui");
	this->ProgramUniform2uiv = (PROC_glProgramUniform2uiv)LoadMethod(PREFIX "glProgramUniform2uiv");
	this->ProgramUniform3i = (PROC_glProgramUniform3i)LoadMethod(PREFIX "glProgramUniform3i");
	this->ProgramUniform3iv = (PROC_glProgramUniform3iv)LoadMethod(PREFIX "glProgramUniform3iv");
	this->ProgramUniform3f = (PROC_glProgramUniform3f)LoadMethod(PREFIX "glProgramUniform3f");
	this->ProgramUniform3fv = (PROC_glProgramUniform3fv)LoadMethod(PREFIX "glProgramUniform3fv");
	this->ProgramUniform3d = (PROC_glProgramUniform3d)LoadMethod(PREFIX "glProgramUniform3d");
	this->ProgramUniform3dv = (PROC_glProgramUniform3dv)LoadMethod(PREFIX "glProgramUniform3dv");
	this->ProgramUniform3ui = (PROC_glProgramUniform3ui)LoadMethod(PREFIX "glProgramUniform3ui");
	this->ProgramUniform3uiv = (PROC_glProgramUniform3uiv)LoadMethod(PREFIX "glProgramUniform3uiv");
	this->ProgramUniform4i = (PROC_glProgramUniform4i)LoadMethod(PREFIX "glProgramUniform4i");
	this->ProgramUniform4iv = (PROC_glProgramUniform4iv)LoadMethod(PREFIX "glProgramUniform4iv");
	this->ProgramUniform4f = (PROC_glProgramUniform4f)LoadMethod(PREFIX "glProgramUniform4f");
	this->ProgramUniform4fv = (PROC_glProgramUniform4fv)LoadMethod(PREFIX "glProgramUniform4fv");
	this->ProgramUniform4d = (PROC_glProgramUniform4d)LoadMethod(PREFIX "glProgramUniform4d");
	this->ProgramUniform4dv = (PROC_glProgramUniform4dv)LoadMethod(PREFIX "glProgramUniform4dv");
	this->ProgramUniform4ui = (PROC_glProgramUniform4ui)LoadMethod(PREFIX "glProgramUniform4ui");
	this->ProgramUniform4uiv = (PROC_glProgramUniform4uiv)LoadMethod(PREFIX "glProgramUniform4uiv");
	this->ProgramUniformMatrix2fv = (PROC_glProgramUniformMatrix2fv)LoadMethod(PREFIX "glProgramUniformMatrix2fv");
	this->ProgramUniformMatrix3fv = (PROC_glProgramUniformMatrix3fv)LoadMethod(PREFIX "glProgramUniformMatrix3fv");
	this->ProgramUniformMatrix4fv = (PROC_glProgramUniformMatrix4fv)LoadMethod(PREFIX "glProgramUniformMatrix4fv");
	this->ProgramUniformMatrix2dv = (PROC_glProgramUniformMatrix2dv)LoadMethod(PREFIX "glProgramUniformMatrix2dv");
	this->ProgramUniformMatrix3dv = (PROC_glProgramUniformMatrix3dv)LoadMethod(PREFIX "glProgramUniformMatrix3dv");
	this->ProgramUniformMatrix4dv = (PROC_glProgramUniformMatrix4dv)LoadMethod(PREFIX "glProgramUniformMatrix4dv");
	this->ProgramUniformMatrix2x3fv = (PROC_glProgramUniformMatrix2x3fv)LoadMethod(PREFIX "glProgramUniformMatrix2x3fv");
	this->ProgramUniformMatrix3x2fv = (PROC_glProgramUniformMatrix3x2fv)LoadMethod(PREFIX "glProgramUniformMatrix3x2fv");
	this->ProgramUniformMatrix2x4fv = (PROC_glProgramUniformMatrix2x4fv)LoadMethod(PREFIX "glProgramUniformMatrix2x4fv");
	this->ProgramUniformMatrix4x2fv = (PROC_glProgramUniformMatrix4x2fv)LoadMethod(PREFIX "glProgramUniformMatrix4x2fv");
	this->ProgramUniformMatrix3x4fv = (PROC_glProgramUniformMatrix3x4fv)LoadMethod(PREFIX "glProgramUniformMatrix3x4fv");
	this->ProgramUniformMatrix4x3fv = (PROC_glProgramUniformMatrix4x3fv)LoadMethod(PREFIX "glProgramUniformMatrix4x3fv");
	this->ProgramUniformMatrix2x3dv = (PROC_glProgramUniformMatrix2x3dv)LoadMethod(PREFIX "glProgramUniformMatrix2x3dv");
	this->ProgramUniformMatrix3x2dv = (PROC_glProgramUniformMatrix3x2dv)LoadMethod(PREFIX "glProgramUniformMatrix3x2dv");
	this->ProgramUniformMatrix2x4dv = (PROC_glProgramUniformMatrix2x4dv)LoadMethod(PREFIX "glProgramUniformMatrix2x4dv");
	this->ProgramUniformMatrix4x2dv = (PROC_glProgramUniformMatrix4x2dv)LoadMethod(PREFIX "glProgramUniformMatrix4x2dv");
	this->ProgramUniformMatrix3x4dv = (PROC_glProgramUniformMatrix3x4dv)LoadMethod(PREFIX "glProgramUniformMatrix3x4dv");
	this->ProgramUniformMatrix4x3dv = (PROC_glProgramUniformMatrix4x3dv)LoadMethod(PREFIX "glProgramUniformMatrix4x3dv");
	this->ValidateProgramPipeline = (PROC_glValidateProgramPipeline)LoadMethod(PREFIX "glValidateProgramPipeline");
	this->GetProgramPipelineInfoLog = (PROC_glGetProgramPipelineInfoLog)LoadMethod(PREFIX "glGetProgramPipelineInfoLog");
	this->VertexAttribL1d = (PROC_glVertexAttribL1d)LoadMethod(PREFIX "glVertexAttribL1d");
	this->VertexAttribL2d = (PROC_glVertexAttribL2d)LoadMethod(PREFIX "glVertexAttribL2d");
	this->VertexAttribL3d = (PROC_glVertexAttribL3d)LoadMethod(PREFIX "glVertexAttribL3d");
	this->VertexAttribL4d = (PROC_glVertexAttribL4d)LoadMethod(PREFIX "glVertexAttribL4d");
	this->VertexAttribL1dv = (PROC_glVertexAttribL1dv)LoadMethod(PREFIX "glVertexAttribL1dv");
	this->VertexAttribL2dv = (PROC_glVertexAttribL2dv)LoadMethod(PREFIX "glVertexAttribL2dv");
	this->VertexAttribL3dv = (PROC_glVertexAttribL3dv)LoadMethod(PREFIX "glVertexAttribL3dv");
	this->VertexAttribL4dv = (PROC_glVertexAttribL4dv)LoadMethod(PREFIX "glVertexAttribL4dv");
	this->VertexAttribLPointer = (PROC_glVertexAttribLPointer)LoadMethod(PREFIX "glVertexAttribLPointer");
	this->GetVertexAttribLdv = (PROC_glGetVertexAttribLdv)LoadMethod(PREFIX "glGetVertexAttribLdv");
	this->ViewportArrayv = (PROC_glViewportArrayv)LoadMethod(PREFIX "glViewportArrayv");
	this->ViewportIndexedf = (PROC_glViewportIndexedf)LoadMethod(PREFIX "glViewportIndexedf");
	this->ViewportIndexedfv = (PROC_glViewportIndexedfv)LoadMethod(PREFIX "glViewportIndexedfv");
	this->ScissorArrayv = (PROC_glScissorArrayv)LoadMethod(PREFIX "glScissorArrayv");
	this->ScissorIndexed = (PROC_glScissorIndexed)LoadMethod(PREFIX "glScissorIndexed");
	this->ScissorIndexedv = (PROC_glScissorIndexedv)LoadMethod(PREFIX "glScissorIndexedv");
	this->DepthRangeArrayv = (PROC_glDepthRangeArrayv)LoadMethod(PREFIX "glDepthRangeArrayv");
	this->DepthRangeIndexed = (PROC_glDepthRangeIndexed)LoadMethod(PREFIX "glDepthRangeIndexed");
	this->GetFloati_v = (PROC_glGetFloati_v)LoadMethod(PREFIX "glGetFloati_v");
	this->GetDoublei_v = (PROC_glGetDoublei_v)LoadMethod(PREFIX "glGetDoublei_v");
	this->DrawArraysInstancedBaseInstance = (PROC_glDrawArraysInstancedBaseInstance)LoadMethod(PREFIX "glDrawArraysInstancedBaseInstance");
	this->DrawElementsInstancedBaseInstance = (PROC_glDrawElementsInstancedBaseInstance)LoadMethod(PREFIX "glDrawElementsInstancedBaseInstance");
	this->DrawElementsInstancedBaseVertexBaseInstance = (PROC_glDrawElementsInstancedBaseVertexBaseInstance)LoadMethod(PREFIX "glDrawElementsInstancedBaseVertexBaseInstance");
	this->GetInternalformativ = (PROC_glGetInternalformativ)LoadMethod(PREFIX "glGetInternalformativ");
	this->GetActiveAtomicCounterBufferiv = (PROC_glGetActiveAtomicCounterBufferiv)LoadMethod(PREFIX "glGetActiveAtomicCounterBufferiv");
	this->BindImageTexture = (PROC_glBindImageTexture)LoadMethod(PREFIX "glBindImageTexture");
	this->MemoryBarrier = (PROC_glMemoryBarrier)LoadMethod(PREFIX "glMemoryBarrier");
	this->TexStorage1D = (PROC_glTexStorage1D)LoadMethod(PREFIX "glTexStorage1D");
	this->TexStorage2D = (PROC_glTexStorage2D)LoadMethod(PREFIX "glTexStorage2D");
	this->TexStorage3D = (PROC_glTexStorage3D)LoadMethod(PREFIX "glTexStorage3D");
	this->DrawTransformFeedbackInstanced = (PROC_glDrawTransformFeedbackInstanced)LoadMethod(PREFIX "glDrawTransformFeedbackInstanced");
	this->DrawTransformFeedbackStreamInstanced = (PROC_glDrawTransformFeedbackStreamInstanced)LoadMethod(PREFIX "glDrawTransformFeedbackStreamInstanced");
	this->ClearBufferData = (PROC_glClearBufferData)LoadMethod(PREFIX "glClearBufferData");
	this->ClearBufferSubData = (PROC_glClearBufferSubData)LoadMethod(PREFIX "glClearBufferSubData");
	this->DispatchCompute = (PROC_glDispatchCompute)LoadMethod(PREFIX "glDispatchCompute");
	this->DispatchComputeIndirect = (PROC_glDispatchComputeIndirect)LoadMethod(PREFIX "glDispatchComputeIndirect");
	this->CopyImageSubData = (PROC_glCopyImageSubData)LoadMethod(PREFIX "glCopyImageSubData");
	this->FramebufferParameteri = (PROC_glFramebufferParameteri)LoadMethod(PREFIX "glFramebufferParameteri");
	this->GetFramebufferParameteriv = (PROC_glGetFramebufferParameteriv)LoadMethod(PREFIX "glGetFramebufferParameteriv");
	this->GetInternalformati64v = (PROC_glGetInternalformati64v)LoadMethod(PREFIX "glGetInternalformati64v");
	this->InvalidateTexSubImage = (PROC_glInvalidateTexSubImage)LoadMethod(PREFIX "glInvalidateTexSubImage");
	this->InvalidateTexImage = (PROC_glInvalidateTexImage)LoadMethod(PREFIX "glInvalidateTexImage");
	this->InvalidateBufferSubData = (PROC_glInvalidateBufferSubData)LoadMethod(PREFIX "glInvalidateBufferSubData");
	this->InvalidateBufferData = (PROC_glInvalidateBufferData)LoadMethod(PREFIX "glInvalidateBufferData");
	this->InvalidateFramebuffer = (PROC_glInvalidateFramebuffer)LoadMethod(PREFIX "glInvalidateFramebuffer");
	this->InvalidateSubFramebuffer = (PROC_glInvalidateSubFramebuffer)LoadMethod(PREFIX "glInvalidateSubFramebuffer");
	this->MultiDrawArraysIndirect = (PROC_glMultiDrawArraysIndirect)LoadMethod(PREFIX "glMultiDrawArraysIndirect");
	this->MultiDrawElementsIndirect = (PROC_glMultiDrawElementsIndirect)LoadMethod(PREFIX "glMultiDrawElementsIndirect");
	this->GetProgramInterfaceiv = (PROC_glGetProgramInterfaceiv)LoadMethod(PREFIX "glGetProgramInterfaceiv");
	this->GetProgramResourceIndex = (PROC_glGetProgramResourceIndex)LoadMethod(PREFIX "glGetProgramResourceIndex");
	this->GetProgramResourceName = (PROC_glGetProgramResourceName)LoadMethod(PREFIX "glGetProgramResourceName");
	this->GetProgramResourceiv = (PROC_glGetProgramResourceiv)LoadMethod(PREFIX "glGetProgramResourceiv");
	this->GetProgramResourceLocation = (PROC_glGetProgramResourceLocation)LoadMethod(PREFIX "glGetProgramResourceLocation");
	this->GetProgramResourceLocationIndex = (PROC_glGetProgramResourceLocationIndex)LoadMethod(PREFIX "glGetProgramResourceLocationIndex");
	this->ShaderStorageBlockBinding = (PROC_glShaderStorageBlockBinding)LoadMethod(PREFIX "glShaderStorageBlockBinding");
	this->TexBufferRange = (PROC_glTexBufferRange)LoadMethod(PREFIX "glTexBufferRange");
	this->TexStorage2DMultisample = (PROC_glTexStorage2DMultisample)LoadMethod(PREFIX "glTexStorage2DMultisample");
	this->TexStorage3DMultisample = (PROC_glTexStorage3DMultisample)LoadMethod(PREFIX "glTexStorage3DMultisample");
	this->TextureView = (PROC_glTextureView)LoadMethod(PREFIX "glTextureView");
	this->BindVertexBuffer = (PROC_glBindVertexBuffer)LoadMethod(PREFIX "glBindVertexBuffer");
	this->VertexAttribFormat = (PROC_glVertexAttribFormat)LoadMethod(PREFIX "glVertexAttribFormat");
	this->VertexAttribIFormat = (PROC_glVertexAttribIFormat)LoadMethod(PREFIX "glVertexAttribIFormat");
	this->VertexAttribLFormat = (PROC_glVertexAttribLFormat)LoadMethod(PREFIX "glVertexAttribLFormat");
	this->VertexAttribBinding = (PROC_glVertexAttribBinding)LoadMethod(PREFIX "glVertexAttribBinding");
	this->VertexBindingDivisor = (PROC_glVertexBindingDivisor)LoadMethod(PREFIX "glVertexBindingDivisor");
	this->DebugMessageControl = (PROC_glDebugMessageControl)LoadMethod(PREFIX "glDebugMessageControl");
	this->DebugMessageInsert = (PROC_glDebugMessageInsert)LoadMethod(PREFIX "glDebugMessageInsert");
	this->DebugMessageCallback = (PROC_glDebugMessageCallback)LoadMethod(PREFIX "glDebugMessageCallback");
	this->GetDebugMessageLog = (PROC_glGetDebugMessageLog)LoadMethod(PREFIX "glGetDebugMessageLog");
	this->PushDebugGroup = (PROC_glPushDebugGroup)LoadMethod(PREFIX "glPushDebugGroup");
	this->PopDebugGroup = (PROC_glPopDebugGroup)LoadMethod(PREFIX "glPopDebugGroup");
	this->ObjectLabel = (PROC_glObjectLabel)LoadMethod(PREFIX "glObjectLabel");
	this->GetObjectLabel = (PROC_glGetObjectLabel)LoadMethod(PREFIX "glGetObjectLabel");
	this->ObjectPtrLabel = (PROC_glObjectPtrLabel)LoadMethod(PREFIX "glObjectPtrLabel");
	this->GetObjectPtrLabel = (PROC_glGetObjectPtrLabel)LoadMethod(PREFIX "glGetObjectPtrLabel");
	this->BufferStorage = (PROC_glBufferStorage)LoadMethod(PREFIX "glBufferStorage");
	this->ClearTexImage = (PROC_glClearTexImage)LoadMethod(PREFIX "glClearTexImage");
	this->ClearTexSubImage = (PROC_glClearTexSubImage)LoadMethod(PREFIX "glClearTexSubImage");
	this->BindBuffersBase = (PROC_glBindBuffersBase)LoadMethod(PREFIX "glBindBuffersBase");
	this->BindBuffersRange = (PROC_glBindBuffersRange)LoadMethod(PREFIX "glBindBuffersRange");
	this->BindTextures = (PROC_glBindTextures)LoadMethod(PREFIX "glBindTextures");
	this->BindSamplers = (PROC_glBindSamplers)LoadMethod(PREFIX "glBindSamplers");
	this->BindImageTextures = (PROC_glBindImageTextures)LoadMethod(PREFIX "glBindImageTextures");
	this->BindVertexBuffers = (PROC_glBindVertexBuffers)LoadMethod(PREFIX "glBindVertexBuffers");
	this->ClipControl = (PROC_glClipControl)LoadMethod(PREFIX "glClipControl");
	this->CreateTransformFeedbacks = (PROC_glCreateTransformFeedbacks)LoadMethod(PREFIX "glCreateTransformFeedbacks");
	this->TransformFeedbackBufferBase = (PROC_glTransformFeedbackBufferBase)LoadMethod(PREFIX "glTransformFeedbackBufferBase");
	this->TransformFeedbackBufferRange = (PROC_glTransformFeedbackBufferRange)LoadMethod(PREFIX "glTransformFeedbackBufferRange");
	this->GetTransformFeedbackiv = (PROC_glGetTransformFeedbackiv)LoadMethod(PREFIX "glGetTransformFeedbackiv");
	this->GetTransformFeedbacki_v = (PROC_glGetTransformFeedbacki_v)LoadMethod(PREFIX "glGetTransformFeedbacki_v");
	this->GetTransformFeedbacki64_v = (PROC_glGetTransformFeedbacki64_v)LoadMethod(PREFIX "glGetTransformFeedbacki64_v");
	this->CreateBuffers = (PROC_glCreateBuffers)LoadMethod(PREFIX "glCreateBuffers");
	this->NamedBufferStorage = (PROC_glNamedBufferStorage)LoadMethod(PREFIX "glNamedBufferStorage");
	this->NamedBufferData = (PROC_glNamedBufferData)LoadMethod(PREFIX "glNamedBufferData");
	this->NamedBufferSubData = (PROC_glNamedBufferSubData)LoadMethod(PREFIX "glNamedBufferSubData");
	this->CopyNamedBufferSubData = (PROC_glCopyNamedBufferSubData)LoadMethod(PREFIX "glCopyNamedBufferSubData");
	this->ClearNamedBufferData = (PROC_glClearNamedBufferData)LoadMethod(PREFIX "glClearNamedBufferData");
	this->ClearNamedBufferSubData = (PROC_glClearNamedBufferSubData)LoadMethod(PREFIX "glClearNamedBufferSubData");
	this->MapNamedBuffer = (PROC_glMapNamedBuffer)LoadMethod(PREFIX "glMapNamedBuffer");
	this->MapNamedBufferRange = (PROC_glMapNamedBufferRange)LoadMethod(PREFIX "glMapNamedBufferRange");
	this->UnmapNamedBuffer = (PROC_glUnmapNamedBuffer)LoadMethod(PREFIX "glUnmapNamedBuffer");
	this->FlushMappedNamedBufferRange = (PROC_glFlushMappedNamedBufferRange)LoadMethod(PREFIX "glFlushMappedNamedBufferRange");
	this->GetNamedBufferParameteriv = (PROC_glGetNamedBufferParameteriv)LoadMethod(PREFIX "glGetNamedBufferParameteriv");
	this->GetNamedBufferParameteri64v = (PROC_glGetNamedBufferParameteri64v)LoadMethod(PREFIX "glGetNamedBufferParameteri64v");
	this->GetNamedBufferPointerv = (PROC_glGetNamedBufferPointerv)LoadMethod(PREFIX "glGetNamedBufferPointerv");
	this->GetNamedBufferSubData = (PROC_glGetNamedBufferSubData)LoadMethod(PREFIX "glGetNamedBufferSubData");
	this->CreateFramebuffers = (PROC_glCreateFramebuffers)LoadMethod(PREFIX "glCreateFramebuffers");
	this->NamedFramebufferRenderbuffer = (PROC_glNamedFramebufferRenderbuffer)LoadMethod(PREFIX "glNamedFramebufferRenderbuffer");
	this->NamedFramebufferParameteri = (PROC_glNamedFramebufferParameteri)LoadMethod(PREFIX "glNamedFramebufferParameteri");
	this->NamedFramebufferTexture = (PROC_glNamedFramebufferTexture)LoadMethod(PREFIX "glNamedFramebufferTexture");
	this->NamedFramebufferTextureLayer = (PROC_glNamedFramebufferTextureLayer)LoadMethod(PREFIX "glNamedFramebufferTextureLayer");
	this->NamedFramebufferDrawBuffer = (PROC_glNamedFramebufferDrawBuffer)LoadMethod(PREFIX "glNamedFramebufferDrawBuffer");
	this->NamedFramebufferDrawBuffers = (PROC_glNamedFramebufferDrawBuffers)LoadMethod(PREFIX "glNamedFramebufferDrawBuffers");
	this->NamedFramebufferReadBuffer = (PROC_glNamedFramebufferReadBuffer)LoadMethod(PREFIX "glNamedFramebufferReadBuffer");
	this->InvalidateNamedFramebufferData = (PROC_glInvalidateNamedFramebufferData)LoadMethod(PREFIX "glInvalidateNamedFramebufferData");
	this->InvalidateNamedFramebufferSubData = (PROC_glInvalidateNamedFramebufferSubData)LoadMethod(PREFIX "glInvalidateNamedFramebufferSubData");
	this->ClearNamedFramebufferiv = (PROC_glClearNamedFramebufferiv)LoadMethod(PREFIX "glClearNamedFramebufferiv");
	this->ClearNamedFramebufferuiv = (PROC_glClearNamedFramebufferuiv)LoadMethod(PREFIX "glClearNamedFramebufferuiv");
	this->ClearNamedFramebufferfv = (PROC_glClearNamedFramebufferfv)LoadMethod(PREFIX "glClearNamedFramebufferfv");
	this->ClearNamedFramebufferfi = (PROC_glClearNamedFramebufferfi)LoadMethod(PREFIX "glClearNamedFramebufferfi");
	this->BlitNamedFramebuffer = (PROC_glBlitNamedFramebuffer)LoadMethod(PREFIX "glBlitNamedFramebuffer");
	this->CheckNamedFramebufferStatus = (PROC_glCheckNamedFramebufferStatus)LoadMethod(PREFIX "glCheckNamedFramebufferStatus");
	this->GetNamedFramebufferParameteriv = (PROC_glGetNamedFramebufferParameteriv)LoadMethod(PREFIX "glGetNamedFramebufferParameteriv");
	this->GetNamedFramebufferAttachmentParameteriv = (PROC_glGetNamedFramebufferAttachmentParameteriv)LoadMethod(PREFIX "glGetNamedFramebufferAttachmentParameteriv");
	this->CreateRenderbuffers = (PROC_glCreateRenderbuffers)LoadMethod(PREFIX "glCreateRenderbuffers");
	this->NamedRenderbufferStorage = (PROC_glNamedRenderbufferStorage)LoadMethod(PREFIX "glNamedRenderbufferStorage");
	this->NamedRenderbufferStorageMultisample = (PROC_glNamedRenderbufferStorageMultisample)LoadMethod(PREFIX "glNamedRenderbufferStorageMultisample");
	this->GetNamedRenderbufferParameteriv = (PROC_glGetNamedRenderbufferParameteriv)LoadMethod(PREFIX "glGetNamedRenderbufferParameteriv");
	this->CreateTextures = (PROC_glCreateTextures)LoadMethod(PREFIX "glCreateTextures");
	this->TextureBuffer = (PROC_glTextureBuffer)LoadMethod(PREFIX "glTextureBuffer");
	this->TextureBufferRange = (PROC_glTextureBufferRange)LoadMethod(PREFIX "glTextureBufferRange");
	this->TextureStorage1D = (PROC_glTextureStorage1D)LoadMethod(PREFIX "glTextureStorage1D");
	this->TextureStorage2D = (PROC_glTextureStorage2D)LoadMethod(PREFIX "glTextureStorage2D");
	this->TextureStorage3D = (PROC_glTextureStorage3D)LoadMethod(PREFIX "glTextureStorage3D");
	this->TextureStorage2DMultisample = (PROC_glTextureStorage2DMultisample)LoadMethod(PREFIX "glTextureStorage2DMultisample");
	this->TextureStorage3DMultisample = (PROC_glTextureStorage3DMultisample)LoadMethod(PREFIX "glTextureStorage3DMultisample");
	this->TextureSubImage1D = (PROC_glTextureSubImage1D)LoadMethod(PREFIX "glTextureSubImage1D");
	this->TextureSubImage2D = (PROC_glTextureSubImage2D)LoadMethod(PREFIX "glTextureSubImage2D");
	this->TextureSubImage3D = (PROC_glTextureSubImage3D)LoadMethod(PREFIX "glTextureSubImage3D");
	this->CompressedTextureSubImage1D = (PROC_glCompressedTextureSubImage1D)LoadMethod(PREFIX "glCompressedTextureSubImage1D");
	this->CompressedTextureSubImage2D = (PROC_glCompressedTextureSubImage2D)LoadMethod(PREFIX "glCompressedTextureSubImage2D");
	this->CompressedTextureSubImage3D = (PROC_glCompressedTextureSubImage3D)LoadMethod(PREFIX "glCompressedTextureSubImage3D");
	this->CopyTextureSubImage1D = (PROC_glCopyTextureSubImage1D)LoadMethod(PREFIX "glCopyTextureSubImage1D");
	this->CopyTextureSubImage2D = (PROC_glCopyTextureSubImage2D)LoadMethod(PREFIX "glCopyTextureSubImage2D");
	this->CopyTextureSubImage3D = (PROC_glCopyTextureSubImage3D)LoadMethod(PREFIX "glCopyTextureSubImage3D");
	this->TextureParameterf = (PROC_glTextureParameterf)LoadMethod(PREFIX "glTextureParameterf");
	this->TextureParameterfv = (PROC_glTextureParameterfv)LoadMethod(PREFIX "glTextureParameterfv");
	this->TextureParameteri = (PROC_glTextureParameteri)LoadMethod(PREFIX "glTextureParameteri");
	this->TextureParameterIiv = (PROC_glTextureParameterIiv)LoadMethod(PREFIX "glTextureParameterIiv");
	this->TextureParameterIuiv = (PROC_glTextureParameterIuiv)LoadMethod(PREFIX "glTextureParameterIuiv");
	this->TextureParameteriv = (PROC_glTextureParameteriv)LoadMethod(PREFIX "glTextureParameteriv");
	this->GenerateTextureMipmap = (PROC_glGenerateTextureMipmap)LoadMethod(PREFIX "glGenerateTextureMipmap");
	this->BindTextureUnit = (PROC_glBindTextureUnit)LoadMethod(PREFIX "glBindTextureUnit");
	this->GetTextureImage = (PROC_glGetTextureImage)LoadMethod(PREFIX "glGetTextureImage");
	this->GetCompressedTextureImage = (PROC_glGetCompressedTextureImage)LoadMethod(PREFIX "glGetCompressedTextureImage");
	this->GetTextureLevelParameterfv = (PROC_glGetTextureLevelParameterfv)LoadMethod(PREFIX "glGetTextureLevelParameterfv");
	this->GetTextureLevelParameteriv = (PROC_glGetTextureLevelParameteriv)LoadMethod(PREFIX "glGetTextureLevelParameteriv");
	this->GetTextureParameterfv = (PROC_glGetTextureParameterfv)LoadMethod(PREFIX "glGetTextureParameterfv");
	this->GetTextureParameterIiv = (PROC_glGetTextureParameterIiv)LoadMethod(PREFIX "glGetTextureParameterIiv");
	this->GetTextureParameterIuiv = (PROC_glGetTextureParameterIuiv)LoadMethod(PREFIX "glGetTextureParameterIuiv");
	this->GetTextureParameteriv = (PROC_glGetTextureParameteriv)LoadMethod(PREFIX "glGetTextureParameteriv");
	this->CreateVertexArrays = (PROC_glCreateVertexArrays)LoadMethod(PREFIX "glCreateVertexArrays");
	this->DisableVertexArrayAttrib = (PROC_glDisableVertexArrayAttrib)LoadMethod(PREFIX "glDisableVertexArrayAttrib");
	this->EnableVertexArrayAttrib = (PROC_glEnableVertexArrayAttrib)LoadMethod(PREFIX "glEnableVertexArrayAttrib");
	this->VertexArrayElementBuffer = (PROC_glVertexArrayElementBuffer)LoadMethod(PREFIX "glVertexArrayElementBuffer");
	this->VertexArrayVertexBuffer = (PROC_glVertexArrayVertexBuffer)LoadMethod(PREFIX "glVertexArrayVertexBuffer");
	this->VertexArrayVertexBuffers = (PROC_glVertexArrayVertexBuffers)LoadMethod(PREFIX "glVertexArrayVertexBuffers");
	this->VertexArrayAttribBinding = (PROC_glVertexArrayAttribBinding)LoadMethod(PREFIX "glVertexArrayAttribBinding");
	this->VertexArrayAttribFormat = (PROC_glVertexArrayAttribFormat)LoadMethod(PREFIX "glVertexArrayAttribFormat");
	this->VertexArrayAttribIFormat = (PROC_glVertexArrayAttribIFormat)LoadMethod(PREFIX "glVertexArrayAttribIFormat");
	this->VertexArrayAttribLFormat = (PROC_glVertexArrayAttribLFormat)LoadMethod(PREFIX "glVertexArrayAttribLFormat");
	this->VertexArrayBindingDivisor = (PROC_glVertexArrayBindingDivisor)LoadMethod(PREFIX "glVertexArrayBindingDivisor");
	this->GetVertexArrayiv = (PROC_glGetVertexArrayiv)LoadMethod(PREFIX "glGetVertexArrayiv");
	this->GetVertexArrayIndexediv = (PROC_glGetVertexArrayIndexediv)LoadMethod(PREFIX "glGetVertexArrayIndexediv");
	this->GetVertexArrayIndexed64iv = (PROC_glGetVertexArrayIndexed64iv)LoadMethod(PREFIX "glGetVertexArrayIndexed64iv");
	this->CreateSamplers = (PROC_glCreateSamplers)LoadMethod(PREFIX "glCreateSamplers");
	this->CreateProgramPipelines = (PROC_glCreateProgramPipelines)LoadMethod(PREFIX "glCreateProgramPipelines");
	this->CreateQueries = (PROC_glCreateQueries)LoadMethod(PREFIX "glCreateQueries");
	this->GetQueryBufferObjecti64v = (PROC_glGetQueryBufferObjecti64v)LoadMethod(PREFIX "glGetQueryBufferObjecti64v");
	this->GetQueryBufferObjectiv = (PROC_glGetQueryBufferObjectiv)LoadMethod(PREFIX "glGetQueryBufferObjectiv");
	this->GetQueryBufferObjectui64v = (PROC_glGetQueryBufferObjectui64v)LoadMethod(PREFIX "glGetQueryBufferObjectui64v");
	this->GetQueryBufferObjectuiv = (PROC_glGetQueryBufferObjectuiv)LoadMethod(PREFIX "glGetQueryBufferObjectuiv");
	this->MemoryBarrierByRegion = (PROC_glMemoryBarrierByRegion)LoadMethod(PREFIX "glMemoryBarrierByRegion");
	this->GetTextureSubImage = (PROC_glGetTextureSubImage)LoadMethod(PREFIX "glGetTextureSubImage");
	this->GetCompressedTextureSubImage = (PROC_glGetCompressedTextureSubImage)LoadMethod(PREFIX "glGetCompressedTextureSubImage");
	this->GetGraphicsResetStatus = (PROC_glGetGraphicsResetStatus)LoadMethod(PREFIX "glGetGraphicsResetStatus");
	this->GetnCompressedTexImage = (PROC_glGetnCompressedTexImage)LoadMethod(PREFIX "glGetnCompressedTexImage");
	this->GetnTexImage = (PROC_glGetnTexImage)LoadMethod(PREFIX "glGetnTexImage");
	this->GetnUniformdv = (PROC_glGetnUniformdv)LoadMethod(PREFIX "glGetnUniformdv");
	this->GetnUniformfv = (PROC_glGetnUniformfv)LoadMethod(PREFIX "glGetnUniformfv");
	this->GetnUniformiv = (PROC_glGetnUniformiv)LoadMethod(PREFIX "glGetnUniformiv");
	this->GetnUniformuiv = (PROC_glGetnUniformuiv)LoadMethod(PREFIX "glGetnUniformuiv");
	this->ReadnPixels = (PROC_glReadnPixels)LoadMethod(PREFIX "glReadnPixels");
	this->TextureBarrier = (PROC_glTextureBarrier)LoadMethod(PREFIX "glTextureBarrier");

	return true;
}
